/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-InterNodeDefinitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_AS_Config_NB_H_
#define	_AS_Config_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioResourceConfigDedicated-NB-r13.h"
#include "SecurityAlgorithmConfig.h"
#include "C-RNTI.h"
#include "CarrierFreq-NB-r13.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CarrierFreq_NB_v1550;

/* AS-Config-NB */
typedef struct AS_Config_NB {
	RadioResourceConfigDedicated_NB_r13_t	 sourceRadioResourceConfig_r13;
	SecurityAlgorithmConfig_t	 sourceSecurityAlgorithmConfig_r13;
	C_RNTI_t	 sourceUE_Identity_r13;
	CarrierFreq_NB_r13_t	 sourceDl_CarrierFreq_r13;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct CarrierFreq_NB_v1550	*sourceDL_CarrierFreq_v1550	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Config_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Config_NB;
extern asn_SEQUENCE_specifics_t asn_SPC_AS_Config_NB_specs_1;
extern asn_TYPE_member_t asn_MBR_AS_Config_NB_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _AS_Config_NB_H_ */
#include <asn_internal.h>
