/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_BCCH_BCH_Message_TDD_NB_H_
#define	_BCCH_BCH_Message_TDD_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BCCH-BCH-MessageType-TDD-NB-r15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BCCH-BCH-Message-TDD-NB */
typedef struct BCCH_BCH_Message_TDD_NB {
	BCCH_BCH_MessageType_TDD_NB_r15_t	 message;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BCCH_BCH_Message_TDD_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BCCH_BCH_Message_TDD_NB;

#ifdef __cplusplus
}
#endif

#endif	/* _BCCH_BCH_Message_TDD_NB_H_ */
#include <asn_internal.h>
