/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_RedirectedCarrierInfo_NB_v1550_H_
#define	_RedirectedCarrierInfo_NB_v1550_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CarrierFreq-NB-v1550.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RedirectedCarrierInfo-NB-v1550 */
typedef CarrierFreq_NB_v1550_t	 RedirectedCarrierInfo_NB_v1550_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RedirectedCarrierInfo_NB_v1550;
asn_struct_free_f RedirectedCarrierInfo_NB_v1550_free;
asn_struct_print_f RedirectedCarrierInfo_NB_v1550_print;
asn_constr_check_f RedirectedCarrierInfo_NB_v1550_constraint;
ber_type_decoder_f RedirectedCarrierInfo_NB_v1550_decode_ber;
der_type_encoder_f RedirectedCarrierInfo_NB_v1550_encode_der;
xer_type_decoder_f RedirectedCarrierInfo_NB_v1550_decode_xer;
xer_type_encoder_f RedirectedCarrierInfo_NB_v1550_encode_xer;
per_type_decoder_f RedirectedCarrierInfo_NB_v1550_decode_uper;
per_type_encoder_f RedirectedCarrierInfo_NB_v1550_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RedirectedCarrierInfo_NB_v1550_H_ */
#include <asn_internal.h>
