/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SchedulingInfo_NB_v1530_H_
#define	_SchedulingInfo_NB_v1530_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SIB_MappingInfo_NB_v1530;

/* SchedulingInfo-NB-v1530 */
typedef struct SchedulingInfo_NB_v1530 {
	struct SIB_MappingInfo_NB_v1530	*sib_MappingInfo_v1530	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SchedulingInfo_NB_v1530_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SchedulingInfo_NB_v1530;
extern asn_SEQUENCE_specifics_t asn_SPC_SchedulingInfo_NB_v1530_specs_1;
extern asn_TYPE_member_t asn_MBR_SchedulingInfo_NB_v1530_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SchedulingInfo_NB_v1530_H_ */
#include <asn_internal.h>
