/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-Sidelink-Preconf"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SL_V2X_TxProfile_r15_H_
#define	_SL_V2X_TxProfile_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SL_V2X_TxProfile_r15 {
	SL_V2X_TxProfile_r15_rel14	= 0,
	SL_V2X_TxProfile_r15_rel15	= 1,
	SL_V2X_TxProfile_r15_spare6	= 2,
	SL_V2X_TxProfile_r15_spare5	= 3,
	SL_V2X_TxProfile_r15_spare4	= 4,
	SL_V2X_TxProfile_r15_spare3	= 5,
	SL_V2X_TxProfile_r15_spare2	= 6,
	SL_V2X_TxProfile_r15_spare1	= 7
	/*
	 * Enumeration is extensible
	 */
} e_SL_V2X_TxProfile_r15;

/* SL-V2X-TxProfile-r15 */
typedef long	 SL_V2X_TxProfile_r15_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SL_V2X_TxProfile_r15_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SL_V2X_TxProfile_r15;
extern const asn_INTEGER_specifics_t asn_SPC_SL_V2X_TxProfile_r15_specs_1;
asn_struct_free_f SL_V2X_TxProfile_r15_free;
asn_struct_print_f SL_V2X_TxProfile_r15_print;
asn_constr_check_f SL_V2X_TxProfile_r15_constraint;
ber_type_decoder_f SL_V2X_TxProfile_r15_decode_ber;
der_type_encoder_f SL_V2X_TxProfile_r15_encode_der;
xer_type_decoder_f SL_V2X_TxProfile_r15_decode_xer;
xer_type_encoder_f SL_V2X_TxProfile_r15_encode_xer;
per_type_decoder_f SL_V2X_TxProfile_r15_decode_uper;
per_type_encoder_f SL_V2X_TxProfile_r15_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_V2X_TxProfile_r15_H_ */
#include <asn_internal.h>
