/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_VarPendingRnaUpdate_r15_H_
#define	_VarPendingRnaUpdate_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VarPendingRnaUpdate-r15 */
typedef struct VarPendingRnaUpdate_r15 {
	BOOLEAN_t	*pendingRnaUpdate	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarPendingRnaUpdate_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarPendingRnaUpdate_r15;

#ifdef __cplusplus
}
#endif

#endif	/* _VarPendingRnaUpdate_r15_H_ */
#include <asn_internal.h>
