/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_GuardbandTDD_NB_r15_H_
#define	_GuardbandTDD_NB_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChannelRasterOffset-NB-r13.h"
#include <NativeEnumerated.h>
#include "SIB-GuardbandAnchorTDD-NB-r15.h"
#include "SIB-GuardbandGuardbandTDD-NB-r15.h"
#include "SIB-GuardbandInbandSamePCI-TDD-NB-r15.h"
#include "SIB-GuardbandInbandDiffPCI-TDD-NB-r15.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR {
	GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR_NOTHING,	/* No components present */
	GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR_sib_GuardbandAnchor_r15,
	GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR_sib_GuardbandGuardband_r15,
	GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR_sib_GuardbandInbandSamePCI_r15,
	GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR_sib_GuardbandinbandDiffPCI_r15
} GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR;
typedef enum GuardbandTDD_NB_r15__eutra_Bandwitdh_r15 {
	GuardbandTDD_NB_r15__eutra_Bandwitdh_r15_bw5or10	= 0,
	GuardbandTDD_NB_r15__eutra_Bandwitdh_r15_bw15or20	= 1
} e_GuardbandTDD_NB_r15__eutra_Bandwitdh_r15;

/* GuardbandTDD-NB-r15 */
typedef struct GuardbandTDD_NB_r15 {
	ChannelRasterOffset_NB_r13_t	 rasterOffset_r15;
	struct GuardbandTDD_NB_r15__sib_GuardbandInfo_r15 {
		GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_PR present;
		union GuardbandTDD_NB_r15__sib_GuardbandInfo_r15_u {
			SIB_GuardbandAnchorTDD_NB_r15_t	 sib_GuardbandAnchor_r15;
			SIB_GuardbandGuardbandTDD_NB_r15_t	 sib_GuardbandGuardband_r15;
			SIB_GuardbandInbandSamePCI_TDD_NB_r15_t	 sib_GuardbandInbandSamePCI_r15;
			SIB_GuardbandInbandDiffPCI_TDD_NB_r15_t	 sib_GuardbandinbandDiffPCI_r15;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sib_GuardbandInfo_r15;
	long	 eutra_Bandwitdh_r15;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GuardbandTDD_NB_r15_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_eutra_Bandwitdh_r15_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_GuardbandTDD_NB_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_GuardbandTDD_NB_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_GuardbandTDD_NB_r15_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _GuardbandTDD_NB_r15_H_ */
#include <asn_internal.h>
