/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "MeasResults.h"

#include "MeasResultForECID-r9.h"
#include "LocationInfo-r10.h"
#include "MeasResultServFreqList-r10.h"
#include "MeasResultCSI-RS-List-r12.h"
#include "MeasResultForRSSI-r13.h"
#include "MeasResultServFreqListExt-r13.h"
#include "MeasResultSSTD-r13.h"
#include "UL-PDCP-DelayResultList-r13.h"
#include "MeasResultListWLAN-r13.h"
#include "MeasResultListCBR-r14.h"
#include "MeasResultListWLAN-r14.h"
#include "MeasResultServFreqListNR-r15.h"
#include "MeasResultCellListSFTD-r15.h"
#include "LogMeasResultListBT-r15.h"
#include "LogMeasResultListWLAN-r15.h"
#include "MeasResultSensing-r15.h"
static int
memb_heightUE_r15_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -400 && value <= 8880)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_measResultNeighCells_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_heightUE_r15_constr_35 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 14,  14, -400,  8880 }	/* (-400..8880) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_measResultPCell_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultPCell, rsrpResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrpResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultPCell, rsrqResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrqResult"
		},
};
static const ber_tlv_tag_t asn_DEF_measResultPCell_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_measResultPCell_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rsrqResult */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResultPCell_specs_3 = {
	sizeof(struct MeasResults__measResultPCell),
	offsetof(struct MeasResults__measResultPCell, _asn_ctx),
	asn_MAP_measResultPCell_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResultPCell_3 = {
	"measResultPCell",
	"measResultPCell",
	&asn_OP_SEQUENCE,
	asn_DEF_measResultPCell_tags_3,
	sizeof(asn_DEF_measResultPCell_tags_3)
		/sizeof(asn_DEF_measResultPCell_tags_3[0]) - 1, /* 1 */
	asn_DEF_measResultPCell_tags_3,	/* Same as above */
	sizeof(asn_DEF_measResultPCell_tags_3)
		/sizeof(asn_DEF_measResultPCell_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_measResultPCell_3,
	2,	/* Elements count */
	&asn_SPC_measResultPCell_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResultNeighCells_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultNeighCells, choice.measResultListEUTRA),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListEUTRA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultNeighCells, choice.measResultListUTRA),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListUTRA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultNeighCells, choice.measResultListGERAN),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListGERAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListGERAN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultNeighCells, choice.measResultsCDMA2000),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultsCDMA2000,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultsCDMA2000"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultNeighCells, choice.measResultNeighCellListNR_r15),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultCellListNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultNeighCellListNR-r15"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_measResultNeighCells_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measResultListEUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultListUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* measResultListGERAN */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* measResultsCDMA2000 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* measResultNeighCellListNR-r15 */
};
static asn_CHOICE_specifics_t asn_SPC_measResultNeighCells_specs_6 = {
	sizeof(struct MeasResults__measResultNeighCells),
	offsetof(struct MeasResults__measResultNeighCells, _asn_ctx),
	offsetof(struct MeasResults__measResultNeighCells, present),
	sizeof(((struct MeasResults__measResultNeighCells *)0)->present),
	asn_MAP_measResultNeighCells_tag2el_6,
	5,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResultNeighCells_6 = {
	"measResultNeighCells",
	"measResultNeighCells",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_measResultNeighCells_constr_6, CHOICE_constraint },
	asn_MBR_measResultNeighCells_6,
	5,	/* Elements count */
	&asn_SPC_measResultNeighCells_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResultPCell_v1310_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults__measResultPCell_v1310, rs_sinr_Result_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RS_SINR_Range_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rs-sinr-Result-r13"
		},
};
static const ber_tlv_tag_t asn_DEF_measResultPCell_v1310_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_measResultPCell_v1310_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* rs-sinr-Result-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResultPCell_v1310_specs_23 = {
	sizeof(struct MeasResults__measResultPCell_v1310),
	offsetof(struct MeasResults__measResultPCell_v1310, _asn_ctx),
	asn_MAP_measResultPCell_v1310_tag2el_23,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResultPCell_v1310_23 = {
	"measResultPCell-v1310",
	"measResultPCell-v1310",
	&asn_OP_SEQUENCE,
	asn_DEF_measResultPCell_v1310_tags_23,
	sizeof(asn_DEF_measResultPCell_v1310_tags_23)
		/sizeof(asn_DEF_measResultPCell_v1310_tags_23[0]) - 1, /* 1 */
	asn_DEF_measResultPCell_v1310_tags_23,	/* Same as above */
	sizeof(asn_DEF_measResultPCell_v1310_tags_23)
		/sizeof(asn_DEF_measResultPCell_v1310_tags_23[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_measResultPCell_v1310_23,
	1,	/* Elements count */
	&asn_SPC_measResultPCell_v1310_specs_23	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MeasResults_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults, measId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResults, measResultPCell),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_measResultPCell_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultPCell"
		},
	{ ATF_POINTER, 22, offsetof(struct MeasResults, measResultNeighCells),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_measResultNeighCells_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultNeighCells"
		},
	{ ATF_POINTER, 21, offsetof(struct MeasResults, measResultForECID_r9),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultForECID_r9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultForECID-r9"
		},
	{ ATF_POINTER, 20, offsetof(struct MeasResults, locationInfo_r10),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocationInfo_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"locationInfo-r10"
		},
	{ ATF_POINTER, 19, offsetof(struct MeasResults, measResultServFreqList_r10),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultServFreqList_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultServFreqList-r10"
		},
	{ ATF_POINTER, 18, offsetof(struct MeasResults, measId_v1250),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasId_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measId-v1250"
		},
	{ ATF_POINTER, 17, offsetof(struct MeasResults, measResultPCell_v1250),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultPCell-v1250"
		},
	{ ATF_POINTER, 16, offsetof(struct MeasResults, measResultCSI_RS_List_r12),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultCSI_RS_List_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultCSI-RS-List-r12"
		},
	{ ATF_POINTER, 15, offsetof(struct MeasResults, measResultForRSSI_r13),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultForRSSI_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultForRSSI-r13"
		},
	{ ATF_POINTER, 14, offsetof(struct MeasResults, measResultServFreqListExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultServFreqListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultServFreqListExt-r13"
		},
	{ ATF_POINTER, 13, offsetof(struct MeasResults, measResultSSTD_r13),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultSSTD_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultSSTD-r13"
		},
	{ ATF_POINTER, 12, offsetof(struct MeasResults, measResultPCell_v1310),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		0,
		&asn_DEF_measResultPCell_v1310_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultPCell-v1310"
		},
	{ ATF_POINTER, 11, offsetof(struct MeasResults, ul_PDCP_DelayResultList_r13),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_PDCP_DelayResultList_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-PDCP-DelayResultList-r13"
		},
	{ ATF_POINTER, 10, offsetof(struct MeasResults, measResultListWLAN_r13),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListWLAN_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListWLAN-r13"
		},
	{ ATF_POINTER, 9, offsetof(struct MeasResults, measResultPCell_v1360),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range_v1360,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultPCell-v1360"
		},
	{ ATF_POINTER, 8, offsetof(struct MeasResults, measResultListCBR_r14),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListCBR_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListCBR-r14"
		},
	{ ATF_POINTER, 7, offsetof(struct MeasResults, measResultListWLAN_r14),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListWLAN_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListWLAN-r14"
		},
	{ ATF_POINTER, 6, offsetof(struct MeasResults, measResultServFreqListNR_r15),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultServFreqListNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultServFreqListNR-r15"
		},
	{ ATF_POINTER, 5, offsetof(struct MeasResults, measResultCellListSFTD_r15),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultCellListSFTD_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultCellListSFTD-r15"
		},
	{ ATF_POINTER, 4, offsetof(struct MeasResults, logMeasResultListBT_r15),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogMeasResultListBT_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logMeasResultListBT-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct MeasResults, logMeasResultListWLAN_r15),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogMeasResultListWLAN_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logMeasResultListWLAN-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasResults, measResultSensing_r15),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultSensing_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultSensing-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResults, heightUE_r15),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_heightUE_r15_constr_35,  memb_heightUE_r15_constraint_1 },
		0, 0, /* No default value */
		"heightUE-r15"
		},
};
static const int asn_MAP_MeasResults_oms_1[] = { 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 };
static const ber_tlv_tag_t asn_DEF_MeasResults_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasResults_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultPCell */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* measResultNeighCells */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* measResultForECID-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* locationInfo-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* measResultServFreqList-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* measId-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* measResultPCell-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* measResultCSI-RS-List-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* measResultForRSSI-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* measResultServFreqListExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* measResultSSTD-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* measResultPCell-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* ul-PDCP-DelayResultList-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* measResultListWLAN-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* measResultPCell-v1360 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* measResultListCBR-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* measResultListWLAN-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* measResultServFreqListNR-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* measResultCellListSFTD-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* logMeasResultListBT-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* logMeasResultListWLAN-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* measResultSensing-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 } /* heightUE-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasResults_specs_1 = {
	sizeof(struct MeasResults),
	offsetof(struct MeasResults, _asn_ctx),
	asn_MAP_MeasResults_tag2el_1,
	24,	/* Count of tags in the map */
	asn_MAP_MeasResults_oms_1,	/* Optional members */
	1, 21,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasResults = {
	"MeasResults",
	"MeasResults",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasResults_tags_1,
	sizeof(asn_DEF_MeasResults_tags_1)
		/sizeof(asn_DEF_MeasResults_tags_1[0]), /* 1 */
	asn_DEF_MeasResults_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasResults_tags_1)
		/sizeof(asn_DEF_MeasResults_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasResults_1,
	24,	/* Elements count */
	&asn_SPC_MeasResults_specs_1	/* Additional specs */
};

