/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "PhysicalConfigDedicated-NB-r13.h"

#include "CarrierConfigDedicated-NB-r13.h"
#include "NPDCCH-ConfigDedicated-NB-r13.h"
#include "NPUSCH-ConfigDedicated-NB-r13.h"
#include "UplinkPowerControlDedicated-NB-r13.h"
#include "NPDCCH-ConfigDedicated-NB-v1530.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_twoHARQ_ProcessesConfig_r14_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_interferenceRandomisationConfig_r14_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_additionalTxSIB1_Config_v1540_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_twoHARQ_ProcessesConfig_r14_value2enum_7[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_twoHARQ_ProcessesConfig_r14_enum2value_7[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_twoHARQ_ProcessesConfig_r14_specs_7 = {
	asn_MAP_twoHARQ_ProcessesConfig_r14_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_twoHARQ_ProcessesConfig_r14_enum2value_7,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_twoHARQ_ProcessesConfig_r14_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_twoHARQ_ProcessesConfig_r14_7 = {
	"twoHARQ-ProcessesConfig-r14",
	"twoHARQ-ProcessesConfig-r14",
	&asn_OP_NativeEnumerated,
	asn_DEF_twoHARQ_ProcessesConfig_r14_tags_7,
	sizeof(asn_DEF_twoHARQ_ProcessesConfig_r14_tags_7)
		/sizeof(asn_DEF_twoHARQ_ProcessesConfig_r14_tags_7[0]) - 1, /* 1 */
	asn_DEF_twoHARQ_ProcessesConfig_r14_tags_7,	/* Same as above */
	sizeof(asn_DEF_twoHARQ_ProcessesConfig_r14_tags_7)
		/sizeof(asn_DEF_twoHARQ_ProcessesConfig_r14_tags_7[0]), /* 2 */
	{ 0, &asn_PER_type_twoHARQ_ProcessesConfig_r14_constr_7, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_twoHARQ_ProcessesConfig_r14_specs_7	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_interferenceRandomisationConfig_r14_value2enum_9[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_interferenceRandomisationConfig_r14_enum2value_9[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_interferenceRandomisationConfig_r14_specs_9 = {
	asn_MAP_interferenceRandomisationConfig_r14_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_interferenceRandomisationConfig_r14_enum2value_9,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_interferenceRandomisationConfig_r14_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_interferenceRandomisationConfig_r14_9 = {
	"interferenceRandomisationConfig-r14",
	"interferenceRandomisationConfig-r14",
	&asn_OP_NativeEnumerated,
	asn_DEF_interferenceRandomisationConfig_r14_tags_9,
	sizeof(asn_DEF_interferenceRandomisationConfig_r14_tags_9)
		/sizeof(asn_DEF_interferenceRandomisationConfig_r14_tags_9[0]) - 1, /* 1 */
	asn_DEF_interferenceRandomisationConfig_r14_tags_9,	/* Same as above */
	sizeof(asn_DEF_interferenceRandomisationConfig_r14_tags_9)
		/sizeof(asn_DEF_interferenceRandomisationConfig_r14_tags_9[0]), /* 2 */
	{ 0, &asn_PER_type_interferenceRandomisationConfig_r14_constr_9, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_interferenceRandomisationConfig_r14_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_additionalTxSIB1_Config_v1540_value2enum_12[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_additionalTxSIB1_Config_v1540_enum2value_12[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_additionalTxSIB1_Config_v1540_specs_12 = {
	asn_MAP_additionalTxSIB1_Config_v1540_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_additionalTxSIB1_Config_v1540_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_additionalTxSIB1_Config_v1540_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_additionalTxSIB1_Config_v1540_12 = {
	"additionalTxSIB1-Config-v1540",
	"additionalTxSIB1-Config-v1540",
	&asn_OP_NativeEnumerated,
	asn_DEF_additionalTxSIB1_Config_v1540_tags_12,
	sizeof(asn_DEF_additionalTxSIB1_Config_v1540_tags_12)
		/sizeof(asn_DEF_additionalTxSIB1_Config_v1540_tags_12[0]) - 1, /* 1 */
	asn_DEF_additionalTxSIB1_Config_v1540_tags_12,	/* Same as above */
	sizeof(asn_DEF_additionalTxSIB1_Config_v1540_tags_12)
		/sizeof(asn_DEF_additionalTxSIB1_Config_v1540_tags_12[0]), /* 2 */
	{ 0, &asn_PER_type_additionalTxSIB1_Config_v1540_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_additionalTxSIB1_Config_v1540_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PhysicalConfigDedicated_NB_r13_1[] = {
	{ ATF_POINTER, 8, offsetof(struct PhysicalConfigDedicated_NB_r13, carrierConfigDedicated_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierConfigDedicated_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"carrierConfigDedicated-r13"
		},
	{ ATF_POINTER, 7, offsetof(struct PhysicalConfigDedicated_NB_r13, npdcch_ConfigDedicated_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NPDCCH_ConfigDedicated_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"npdcch-ConfigDedicated-r13"
		},
	{ ATF_POINTER, 6, offsetof(struct PhysicalConfigDedicated_NB_r13, npusch_ConfigDedicated_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NPUSCH_ConfigDedicated_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"npusch-ConfigDedicated-r13"
		},
	{ ATF_POINTER, 5, offsetof(struct PhysicalConfigDedicated_NB_r13, uplinkPowerControlDedicated_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlDedicated_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlDedicated-r13"
		},
	{ ATF_POINTER, 4, offsetof(struct PhysicalConfigDedicated_NB_r13, twoHARQ_ProcessesConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_twoHARQ_ProcessesConfig_r14_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"twoHARQ-ProcessesConfig-r14"
		},
	{ ATF_POINTER, 3, offsetof(struct PhysicalConfigDedicated_NB_r13, interferenceRandomisationConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_interferenceRandomisationConfig_r14_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interferenceRandomisationConfig-r14"
		},
	{ ATF_POINTER, 2, offsetof(struct PhysicalConfigDedicated_NB_r13, npdcch_ConfigDedicated_v1530),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NPDCCH_ConfigDedicated_NB_v1530,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"npdcch-ConfigDedicated-v1530"
		},
	{ ATF_POINTER, 1, offsetof(struct PhysicalConfigDedicated_NB_r13, additionalTxSIB1_Config_v1540),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_additionalTxSIB1_Config_v1540_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalTxSIB1-Config-v1540"
		},
};
static const int asn_MAP_PhysicalConfigDedicated_NB_r13_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_PhysicalConfigDedicated_NB_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PhysicalConfigDedicated_NB_r13_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierConfigDedicated-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* npdcch-ConfigDedicated-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* npusch-ConfigDedicated-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* uplinkPowerControlDedicated-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* twoHARQ-ProcessesConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* interferenceRandomisationConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* npdcch-ConfigDedicated-v1530 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* additionalTxSIB1-Config-v1540 */
};
asn_SEQUENCE_specifics_t asn_SPC_PhysicalConfigDedicated_NB_r13_specs_1 = {
	sizeof(struct PhysicalConfigDedicated_NB_r13),
	offsetof(struct PhysicalConfigDedicated_NB_r13, _asn_ctx),
	asn_MAP_PhysicalConfigDedicated_NB_r13_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_PhysicalConfigDedicated_NB_r13_oms_1,	/* Optional members */
	4, 4,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PhysicalConfigDedicated_NB_r13 = {
	"PhysicalConfigDedicated-NB-r13",
	"PhysicalConfigDedicated-NB-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_PhysicalConfigDedicated_NB_r13_tags_1,
	sizeof(asn_DEF_PhysicalConfigDedicated_NB_r13_tags_1)
		/sizeof(asn_DEF_PhysicalConfigDedicated_NB_r13_tags_1[0]), /* 1 */
	asn_DEF_PhysicalConfigDedicated_NB_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_PhysicalConfigDedicated_NB_r13_tags_1)
		/sizeof(asn_DEF_PhysicalConfigDedicated_NB_r13_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PhysicalConfigDedicated_NB_r13_1,
	8,	/* Elements count */
	&asn_SPC_PhysicalConfigDedicated_NB_r13_specs_1	/* Additional specs */
};

