/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "RadioResourceConfigDedicated.h"

#include "SRB-ToAddModList.h"
#include "DRB-ToAddModList.h"
#include "DRB-ToReleaseList.h"
#include "SPS-Config.h"
#include "PhysicalConfigDedicated.h"
#include "RLF-TimersAndConstants-r9.h"
#include "MeasSubframePatternPCell-r10.h"
#include "NeighCellsCRS-Info-r11.h"
#include "NAICS-AssistanceInfo-r12.h"
#include "NeighCellsCRS-Info-r13.h"
#include "RLF-TimersAndConstants-r13.h"
#include "SPS-Config-v1430.h"
#include "SRB-ToAddModListExt-r15.h"
#include "SPS-Config-v1530.h"
#include "NeighCellsCRS-Info-r15.h"
#include "DRB-ToAddModList-r15.h"
#include "DRB-ToReleaseList-r15.h"
#include "SPS-Config-v1540.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_NativeInteger_constraint_31(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_srb_ToReleaseListExt_r15_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value == 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_dummy_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 2)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_mac_MainConfig_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_crs_IntfMitigNumPRBs_r15_constr_25 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_setup_constr_23 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_crs_IntfMitigConfig_r15_constr_21 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_Member_constr_32 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (1..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_dummy_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_srb_ToReleaseListExt_r15_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  4,  4 }	/* (4..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_dummy_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_mac_MainConfig_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigDedicated__mac_MainConfig, choice.explicitValue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAC_MainConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"explicitValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigDedicated__mac_MainConfig, choice.defaultValue),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultValue"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_mac_MainConfig_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* explicitValue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* defaultValue */
};
static asn_CHOICE_specifics_t asn_SPC_mac_MainConfig_specs_5 = {
	sizeof(struct RadioResourceConfigDedicated__mac_MainConfig),
	offsetof(struct RadioResourceConfigDedicated__mac_MainConfig, _asn_ctx),
	offsetof(struct RadioResourceConfigDedicated__mac_MainConfig, present),
	sizeof(((struct RadioResourceConfigDedicated__mac_MainConfig *)0)->present),
	asn_MAP_mac_MainConfig_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mac_MainConfig_5 = {
	"mac-MainConfig",
	"mac-MainConfig",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_mac_MainConfig_constr_5, CHOICE_constraint },
	asn_MBR_mac_MainConfig_5,
	2,	/* Elements count */
	&asn_SPC_mac_MainConfig_specs_5	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_crs_IntfMitigNumPRBs_r15_value2enum_25[] = {
	{ 0,	2,	"n6" },
	{ 1,	3,	"n24" }
};
static const unsigned int asn_MAP_crs_IntfMitigNumPRBs_r15_enum2value_25[] = {
	1,	/* n24(1) */
	0	/* n6(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_crs_IntfMitigNumPRBs_r15_specs_25 = {
	asn_MAP_crs_IntfMitigNumPRBs_r15_value2enum_25,	/* "tag" => N; sorted by tag */
	asn_MAP_crs_IntfMitigNumPRBs_r15_enum2value_25,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_crs_IntfMitigNumPRBs_r15_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crs_IntfMitigNumPRBs_r15_25 = {
	"crs-IntfMitigNumPRBs-r15",
	"crs-IntfMitigNumPRBs-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_crs_IntfMitigNumPRBs_r15_tags_25,
	sizeof(asn_DEF_crs_IntfMitigNumPRBs_r15_tags_25)
		/sizeof(asn_DEF_crs_IntfMitigNumPRBs_r15_tags_25[0]) - 1, /* 1 */
	asn_DEF_crs_IntfMitigNumPRBs_r15_tags_25,	/* Same as above */
	sizeof(asn_DEF_crs_IntfMitigNumPRBs_r15_tags_25)
		/sizeof(asn_DEF_crs_IntfMitigNumPRBs_r15_tags_25[0]), /* 2 */
	{ 0, &asn_PER_type_crs_IntfMitigNumPRBs_r15_constr_25, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_crs_IntfMitigNumPRBs_r15_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15__setup, choice.crs_IntfMitigEnabled_15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crs-IntfMitigEnabled-15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15__setup, choice.crs_IntfMitigNumPRBs_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_crs_IntfMitigNumPRBs_r15_25,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crs-IntfMitigNumPRBs-r15"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* crs-IntfMitigEnabled-15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* crs-IntfMitigNumPRBs-r15 */
};
static asn_CHOICE_specifics_t asn_SPC_setup_specs_23 = {
	sizeof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15__setup),
	offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15__setup, _asn_ctx),
	offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15__setup, present),
	sizeof(((struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15__setup *)0)->present),
	asn_MAP_setup_tag2el_23,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_23 = {
	"setup",
	"setup",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_setup_constr_23, CHOICE_constraint },
	asn_MBR_setup_23,
	2,	/* Elements count */
	&asn_SPC_setup_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_crs_IntfMitigConfig_r15_21[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_setup_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_crs_IntfMitigConfig_r15_tag2el_21[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_crs_IntfMitigConfig_r15_specs_21 = {
	sizeof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15),
	offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15, _asn_ctx),
	offsetof(struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15, present),
	sizeof(((struct RadioResourceConfigDedicated__crs_IntfMitigConfig_r15 *)0)->present),
	asn_MAP_crs_IntfMitigConfig_r15_tag2el_21,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crs_IntfMitigConfig_r15_21 = {
	"crs-IntfMitigConfig-r15",
	"crs-IntfMitigConfig-r15",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_crs_IntfMitigConfig_r15_constr_21, CHOICE_constraint },
	asn_MBR_crs_IntfMitigConfig_r15_21,
	2,	/* Elements count */
	&asn_SPC_crs_IntfMitigConfig_r15_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_dummy_31[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_Member_constr_32,  memb_NativeInteger_constraint_31 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_dummy_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_dummy_specs_31 = {
	sizeof(struct RadioResourceConfigDedicated__dummy),
	offsetof(struct RadioResourceConfigDedicated__dummy, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dummy_31 = {
	"dummy",
	"dummy",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_dummy_tags_31,
	sizeof(asn_DEF_dummy_tags_31)
		/sizeof(asn_DEF_dummy_tags_31[0]) - 1, /* 1 */
	asn_DEF_dummy_tags_31,	/* Same as above */
	sizeof(asn_DEF_dummy_tags_31)
		/sizeof(asn_DEF_dummy_tags_31[0]), /* 2 */
	{ 0, &asn_PER_type_dummy_constr_31, SEQUENCE_OF_constraint },
	asn_MBR_dummy_31,
	1,	/* Single element */
	&asn_SPC_dummy_specs_31	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RadioResourceConfigDedicated_1[] = {
	{ ATF_POINTER, 22, offsetof(struct RadioResourceConfigDedicated, srb_ToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRB_ToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srb-ToAddModList"
		},
	{ ATF_POINTER, 21, offsetof(struct RadioResourceConfigDedicated, drb_ToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToAddModList"
		},
	{ ATF_POINTER, 20, offsetof(struct RadioResourceConfigDedicated, drb_ToReleaseList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToReleaseList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToReleaseList"
		},
	{ ATF_POINTER, 19, offsetof(struct RadioResourceConfigDedicated, mac_MainConfig),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_mac_MainConfig_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mac-MainConfig"
		},
	{ ATF_POINTER, 18, offsetof(struct RadioResourceConfigDedicated, sps_Config),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPS_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sps-Config"
		},
	{ ATF_POINTER, 17, offsetof(struct RadioResourceConfigDedicated, physicalConfigDedicated),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysicalConfigDedicated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"physicalConfigDedicated"
		},
	{ ATF_POINTER, 16, offsetof(struct RadioResourceConfigDedicated, rlf_TimersAndConstants_r9),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RLF_TimersAndConstants_r9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlf-TimersAndConstants-r9"
		},
	{ ATF_POINTER, 15, offsetof(struct RadioResourceConfigDedicated, measSubframePatternPCell_r10),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MeasSubframePatternPCell_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measSubframePatternPCell-r10"
		},
	{ ATF_POINTER, 14, offsetof(struct RadioResourceConfigDedicated, neighCellsCRS_Info_r11),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NeighCellsCRS_Info_r11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"neighCellsCRS-Info-r11"
		},
	{ ATF_POINTER, 13, offsetof(struct RadioResourceConfigDedicated, naics_Info_r12),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NAICS_AssistanceInfo_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"naics-Info-r12"
		},
	{ ATF_POINTER, 12, offsetof(struct RadioResourceConfigDedicated, neighCellsCRS_Info_r13),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NeighCellsCRS_Info_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"neighCellsCRS-Info-r13"
		},
	{ ATF_POINTER, 11, offsetof(struct RadioResourceConfigDedicated, rlf_TimersAndConstants_r13),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RLF_TimersAndConstants_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlf-TimersAndConstants-r13"
		},
	{ ATF_POINTER, 10, offsetof(struct RadioResourceConfigDedicated, sps_Config_v1430),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPS_Config_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sps-Config-v1430"
		},
	{ ATF_POINTER, 9, offsetof(struct RadioResourceConfigDedicated, srb_ToAddModListExt_r15),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRB_ToAddModListExt_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srb-ToAddModListExt-r15"
		},
	{ ATF_POINTER, 8, offsetof(struct RadioResourceConfigDedicated, srb_ToReleaseListExt_r15),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_srb_ToReleaseListExt_r15_constr_19,  memb_srb_ToReleaseListExt_r15_constraint_1 },
		0, 0, /* No default value */
		"srb-ToReleaseListExt-r15"
		},
	{ ATF_POINTER, 7, offsetof(struct RadioResourceConfigDedicated, sps_Config_v1530),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPS_Config_v1530,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sps-Config-v1530"
		},
	{ ATF_POINTER, 6, offsetof(struct RadioResourceConfigDedicated, crs_IntfMitigConfig_r15),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_crs_IntfMitigConfig_r15_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crs-IntfMitigConfig-r15"
		},
	{ ATF_POINTER, 5, offsetof(struct RadioResourceConfigDedicated, neighCellsCRS_Info_r15),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NeighCellsCRS_Info_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"neighCellsCRS-Info-r15"
		},
	{ ATF_POINTER, 4, offsetof(struct RadioResourceConfigDedicated, drb_ToAddModList_r15),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToAddModList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToAddModList-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct RadioResourceConfigDedicated, drb_ToReleaseList_r15),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToReleaseList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToReleaseList-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct RadioResourceConfigDedicated, dummy),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		0,
		&asn_DEF_dummy_31,
		0,
		{ 0, &asn_PER_memb_dummy_constr_31,  memb_dummy_constraint_1 },
		0, 0, /* No default value */
		"dummy"
		},
	{ ATF_POINTER, 1, offsetof(struct RadioResourceConfigDedicated, sps_Config_v1540),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPS_Config_v1540,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sps-Config-v1540"
		},
};
static const int asn_MAP_RadioResourceConfigDedicated_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21 };
static const ber_tlv_tag_t asn_DEF_RadioResourceConfigDedicated_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RadioResourceConfigDedicated_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* srb-ToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* drb-ToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* drb-ToReleaseList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mac-MainConfig */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sps-Config */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* physicalConfigDedicated */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* rlf-TimersAndConstants-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* measSubframePatternPCell-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* neighCellsCRS-Info-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* naics-Info-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* neighCellsCRS-Info-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* rlf-TimersAndConstants-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* sps-Config-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* srb-ToAddModListExt-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* srb-ToReleaseListExt-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* sps-Config-v1530 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* crs-IntfMitigConfig-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* neighCellsCRS-Info-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* drb-ToAddModList-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* drb-ToReleaseList-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* dummy */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 } /* sps-Config-v1540 */
};
asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigDedicated_specs_1 = {
	sizeof(struct RadioResourceConfigDedicated),
	offsetof(struct RadioResourceConfigDedicated, _asn_ctx),
	asn_MAP_RadioResourceConfigDedicated_tag2el_1,
	22,	/* Count of tags in the map */
	asn_MAP_RadioResourceConfigDedicated_oms_1,	/* Optional members */
	6, 16,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigDedicated = {
	"RadioResourceConfigDedicated",
	"RadioResourceConfigDedicated",
	&asn_OP_SEQUENCE,
	asn_DEF_RadioResourceConfigDedicated_tags_1,
	sizeof(asn_DEF_RadioResourceConfigDedicated_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicated_tags_1[0]), /* 1 */
	asn_DEF_RadioResourceConfigDedicated_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadioResourceConfigDedicated_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicated_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RadioResourceConfigDedicated_1,
	22,	/* Elements count */
	&asn_SPC_RadioResourceConfigDedicated_specs_1	/* Additional specs */
};

