/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SCG_Config_v12i0_IEs_H_
#define	_SCG_Config_v12i0_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SCG_ConfigPartSCG_v12f0;

/* SCG-Config-v12i0-IEs */
typedef struct SCG_Config_v12i0_IEs {
	struct SCG_ConfigPartSCG_v12f0	*scg_RadioConfig_v12i0	/* OPTIONAL */;
	struct SCG_Config_v12i0_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCG_Config_v12i0_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCG_Config_v12i0_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _SCG_Config_v12i0_IEs_H_ */
#include <asn_internal.h>
