/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-Sidelink-Preconf"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SL_PPPP_TxPreconfigIndex_v1530_H_
#define	_SL_PPPP_TxPreconfigIndex_v1530_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MCS_PSSCH_Range_r15;

/* SL-PPPP-TxPreconfigIndex-v1530 */
typedef struct SL_PPPP_TxPreconfigIndex_v1530 {
	struct SL_PPPP_TxPreconfigIndex_v1530__mcs_PSSCH_Range_r15 {
		A_SEQUENCE_OF(struct MCS_PSSCH_Range_r15) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *mcs_PSSCH_Range_r15;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_PPPP_TxPreconfigIndex_v1530_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_PPPP_TxPreconfigIndex_v1530;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_PPPP_TxPreconfigIndex_v1530_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_PPPP_TxPreconfigIndex_v1530_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_PPPP_TxPreconfigIndex_v1530_H_ */
#include <asn_internal.h>
