/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "SL-V2X-ConfigDedicated-r14.h"

#include "SL-InterFreqInfoListV2X-r14.h"
#include "SL-CBR-CommonTxConfigList-r14.h"
#include "SL-V2X-PacketDuplicationConfig-r15.h"
#include "SL-V2X-SyncFreqList-r15.h"
#include "SL-CommResourcePoolV2X-r14.h"
#include "SL-TxPoolToReleaseListV2X-r14.h"
#include "SL-TxPoolToAddModListV2X-r14.h"
#include "SL-CommTxPoolSensingConfig-r14.h"
#include "LogicalChGroupInfoList-v1530.h"
#include "SL-V2X-FreqSelectionConfigList-r15.h"
static int
memb_mcs_r14_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 31)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_mcs_r15_constraint_24(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 31)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_memb_mcs_r14_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_setup_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_commTxResources_r14_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_mcs_r15_constr_26 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_setup_constr_23 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_commTxResources_v1530_constr_21 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_slss_TxMultiFreq_r15_constr_31 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_slss_TxDisabled_r15_constr_33 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_scheduled_r14_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__scheduled_r14, sl_V_RNTI_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_C_RNTI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl-V-RNTI-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__scheduled_r14, mac_MainConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAC_MainConfigSL_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mac-MainConfig-r14"
		},
	{ ATF_POINTER, 2, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__scheduled_r14, v2x_SchedulingPool_r14),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CommResourcePoolV2X_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2x-SchedulingPool-r14"
		},
	{ ATF_POINTER, 1, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__scheduled_r14, mcs_r14),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_mcs_r14_constr_9,  memb_mcs_r14_constraint_5 },
		0, 0, /* No default value */
		"mcs-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__scheduled_r14, logicalChGroupInfoList_r14),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogicalChGroupInfoList_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logicalChGroupInfoList-r14"
		},
};
static const int asn_MAP_scheduled_r14_oms_5[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_scheduled_r14_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_scheduled_r14_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl-V-RNTI-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mac-MainConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* v2x-SchedulingPool-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* mcs-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* logicalChGroupInfoList-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_scheduled_r14_specs_5 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__scheduled_r14),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__scheduled_r14, _asn_ctx),
	asn_MAP_scheduled_r14_tag2el_5,
	5,	/* Count of tags in the map */
	asn_MAP_scheduled_r14_oms_5,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scheduled_r14_5 = {
	"scheduled-r14",
	"scheduled-r14",
	&asn_OP_SEQUENCE,
	asn_DEF_scheduled_r14_tags_5,
	sizeof(asn_DEF_scheduled_r14_tags_5)
		/sizeof(asn_DEF_scheduled_r14_tags_5[0]) - 1, /* 1 */
	asn_DEF_scheduled_r14_tags_5,	/* Same as above */
	sizeof(asn_DEF_scheduled_r14_tags_5)
		/sizeof(asn_DEF_scheduled_r14_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_scheduled_r14_5,
	5,	/* Elements count */
	&asn_SPC_scheduled_r14_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v2x_CommTxPoolNormalDedicated_r14_12[] = {
	{ ATF_POINTER, 3, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14__v2x_CommTxPoolNormalDedicated_r14, poolToReleaseList_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_TxPoolToReleaseListV2X_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"poolToReleaseList-r14"
		},
	{ ATF_POINTER, 2, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14__v2x_CommTxPoolNormalDedicated_r14, poolToAddModList_r14),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_TxPoolToAddModListV2X_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"poolToAddModList-r14"
		},
	{ ATF_POINTER, 1, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14__v2x_CommTxPoolNormalDedicated_r14, v2x_CommTxPoolSensingConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CommTxPoolSensingConfig_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2x-CommTxPoolSensingConfig-r14"
		},
};
static const int asn_MAP_v2x_CommTxPoolNormalDedicated_r14_oms_12[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_v2x_CommTxPoolNormalDedicated_r14_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v2x_CommTxPoolNormalDedicated_r14_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* poolToReleaseList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* poolToAddModList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* v2x-CommTxPoolSensingConfig-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v2x_CommTxPoolNormalDedicated_r14_specs_12 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14__v2x_CommTxPoolNormalDedicated_r14),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14__v2x_CommTxPoolNormalDedicated_r14, _asn_ctx),
	asn_MAP_v2x_CommTxPoolNormalDedicated_r14_tag2el_12,
	3,	/* Count of tags in the map */
	asn_MAP_v2x_CommTxPoolNormalDedicated_r14_oms_12,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v2x_CommTxPoolNormalDedicated_r14_12 = {
	"v2x-CommTxPoolNormalDedicated-r14",
	"v2x-CommTxPoolNormalDedicated-r14",
	&asn_OP_SEQUENCE,
	asn_DEF_v2x_CommTxPoolNormalDedicated_r14_tags_12,
	sizeof(asn_DEF_v2x_CommTxPoolNormalDedicated_r14_tags_12)
		/sizeof(asn_DEF_v2x_CommTxPoolNormalDedicated_r14_tags_12[0]) - 1, /* 1 */
	asn_DEF_v2x_CommTxPoolNormalDedicated_r14_tags_12,	/* Same as above */
	sizeof(asn_DEF_v2x_CommTxPoolNormalDedicated_r14_tags_12)
		/sizeof(asn_DEF_v2x_CommTxPoolNormalDedicated_r14_tags_12[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_v2x_CommTxPoolNormalDedicated_r14_12,
	3,	/* Elements count */
	&asn_SPC_v2x_CommTxPoolNormalDedicated_r14_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ue_Selected_r14_11[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14, v2x_CommTxPoolNormalDedicated_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_v2x_CommTxPoolNormalDedicated_r14_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2x-CommTxPoolNormalDedicated-r14"
		},
};
static const ber_tlv_tag_t asn_DEF_ue_Selected_r14_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ue_Selected_r14_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* v2x-CommTxPoolNormalDedicated-r14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ue_Selected_r14_specs_11 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup__ue_Selected_r14, _asn_ctx),
	asn_MAP_ue_Selected_r14_tag2el_11,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ue_Selected_r14_11 = {
	"ue-Selected-r14",
	"ue-Selected-r14",
	&asn_OP_SEQUENCE,
	asn_DEF_ue_Selected_r14_tags_11,
	sizeof(asn_DEF_ue_Selected_r14_tags_11)
		/sizeof(asn_DEF_ue_Selected_r14_tags_11[0]) - 1, /* 1 */
	asn_DEF_ue_Selected_r14_tags_11,	/* Same as above */
	sizeof(asn_DEF_ue_Selected_r14_tags_11)
		/sizeof(asn_DEF_ue_Selected_r14_tags_11[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ue_Selected_r14_11,
	1,	/* Elements count */
	&asn_SPC_ue_Selected_r14_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup, choice.scheduled_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_scheduled_r14_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scheduled-r14"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup, choice.ue_Selected_r14),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ue_Selected_r14_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Selected-r14"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scheduled-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-Selected-r14 */
};
static asn_CHOICE_specifics_t asn_SPC_setup_specs_4 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup, _asn_ctx),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup, present),
	sizeof(((struct SL_V2X_ConfigDedicated_r14__commTxResources_r14__setup *)0)->present),
	asn_MAP_setup_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_4 = {
	"setup",
	"setup",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_setup_constr_4, CHOICE_constraint },
	asn_MBR_setup_4,
	2,	/* Elements count */
	&asn_SPC_setup_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_commTxResources_r14_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_setup_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_commTxResources_r14_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_commTxResources_r14_specs_2 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14, _asn_ctx),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_r14, present),
	sizeof(((struct SL_V2X_ConfigDedicated_r14__commTxResources_r14 *)0)->present),
	asn_MAP_commTxResources_r14_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_commTxResources_r14_2 = {
	"commTxResources-r14",
	"commTxResources-r14",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_commTxResources_r14_constr_2, CHOICE_constraint },
	asn_MBR_commTxResources_r14_2,
	2,	/* Elements count */
	&asn_SPC_commTxResources_r14_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_scheduled_v1530_24[] = {
	{ ATF_POINTER, 2, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup__scheduled_v1530, logicalChGroupInfoList_v1530),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogicalChGroupInfoList_v1530,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logicalChGroupInfoList-v1530"
		},
	{ ATF_POINTER, 1, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup__scheduled_v1530, mcs_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_mcs_r15_constr_26,  memb_mcs_r15_constraint_24 },
		0, 0, /* No default value */
		"mcs-r15"
		},
};
static const int asn_MAP_scheduled_v1530_oms_24[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_scheduled_v1530_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_scheduled_v1530_tag2el_24[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* logicalChGroupInfoList-v1530 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* mcs-r15 */
};
static asn_SEQUENCE_specifics_t asn_SPC_scheduled_v1530_specs_24 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup__scheduled_v1530),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup__scheduled_v1530, _asn_ctx),
	asn_MAP_scheduled_v1530_tag2el_24,
	2,	/* Count of tags in the map */
	asn_MAP_scheduled_v1530_oms_24,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_scheduled_v1530_24 = {
	"scheduled-v1530",
	"scheduled-v1530",
	&asn_OP_SEQUENCE,
	asn_DEF_scheduled_v1530_tags_24,
	sizeof(asn_DEF_scheduled_v1530_tags_24)
		/sizeof(asn_DEF_scheduled_v1530_tags_24[0]) - 1, /* 1 */
	asn_DEF_scheduled_v1530_tags_24,	/* Same as above */
	sizeof(asn_DEF_scheduled_v1530_tags_24)
		/sizeof(asn_DEF_scheduled_v1530_tags_24[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_scheduled_v1530_24,
	2,	/* Elements count */
	&asn_SPC_scheduled_v1530_specs_24	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ue_Selected_v1530_27[] = {
	{ ATF_POINTER, 1, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup__ue_Selected_v1530, v2x_FreqSelectionConfigList_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_V2X_FreqSelectionConfigList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2x-FreqSelectionConfigList-r15"
		},
};
static const int asn_MAP_ue_Selected_v1530_oms_27[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ue_Selected_v1530_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ue_Selected_v1530_tag2el_27[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* v2x-FreqSelectionConfigList-r15 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ue_Selected_v1530_specs_27 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup__ue_Selected_v1530),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup__ue_Selected_v1530, _asn_ctx),
	asn_MAP_ue_Selected_v1530_tag2el_27,
	1,	/* Count of tags in the map */
	asn_MAP_ue_Selected_v1530_oms_27,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ue_Selected_v1530_27 = {
	"ue-Selected-v1530",
	"ue-Selected-v1530",
	&asn_OP_SEQUENCE,
	asn_DEF_ue_Selected_v1530_tags_27,
	sizeof(asn_DEF_ue_Selected_v1530_tags_27)
		/sizeof(asn_DEF_ue_Selected_v1530_tags_27[0]) - 1, /* 1 */
	asn_DEF_ue_Selected_v1530_tags_27,	/* Same as above */
	sizeof(asn_DEF_ue_Selected_v1530_tags_27)
		/sizeof(asn_DEF_ue_Selected_v1530_tags_27[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ue_Selected_v1530_27,
	1,	/* Elements count */
	&asn_SPC_ue_Selected_v1530_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup, choice.scheduled_v1530),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_scheduled_v1530_24,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scheduled-v1530"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup, choice.ue_Selected_v1530),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ue_Selected_v1530_27,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Selected-v1530"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scheduled-v1530 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-Selected-v1530 */
};
static asn_CHOICE_specifics_t asn_SPC_setup_specs_23 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup, _asn_ctx),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup, present),
	sizeof(((struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530__setup *)0)->present),
	asn_MAP_setup_tag2el_23,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_23 = {
	"setup",
	"setup",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_setup_constr_23, CHOICE_constraint },
	asn_MBR_setup_23,
	2,	/* Elements count */
	&asn_SPC_setup_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_commTxResources_v1530_21[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_setup_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_commTxResources_v1530_tag2el_21[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_commTxResources_v1530_specs_21 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530, _asn_ctx),
	offsetof(struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530, present),
	sizeof(((struct SL_V2X_ConfigDedicated_r14__commTxResources_v1530 *)0)->present),
	asn_MAP_commTxResources_v1530_tag2el_21,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_commTxResources_v1530_21 = {
	"commTxResources-v1530",
	"commTxResources-v1530",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_commTxResources_v1530_constr_21, CHOICE_constraint },
	asn_MBR_commTxResources_v1530_21,
	2,	/* Elements count */
	&asn_SPC_commTxResources_v1530_specs_21	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_slss_TxMultiFreq_r15_value2enum_31[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_slss_TxMultiFreq_r15_enum2value_31[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_slss_TxMultiFreq_r15_specs_31 = {
	asn_MAP_slss_TxMultiFreq_r15_value2enum_31,	/* "tag" => N; sorted by tag */
	asn_MAP_slss_TxMultiFreq_r15_enum2value_31,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_slss_TxMultiFreq_r15_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_slss_TxMultiFreq_r15_31 = {
	"slss-TxMultiFreq-r15",
	"slss-TxMultiFreq-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_slss_TxMultiFreq_r15_tags_31,
	sizeof(asn_DEF_slss_TxMultiFreq_r15_tags_31)
		/sizeof(asn_DEF_slss_TxMultiFreq_r15_tags_31[0]) - 1, /* 1 */
	asn_DEF_slss_TxMultiFreq_r15_tags_31,	/* Same as above */
	sizeof(asn_DEF_slss_TxMultiFreq_r15_tags_31)
		/sizeof(asn_DEF_slss_TxMultiFreq_r15_tags_31[0]), /* 2 */
	{ 0, &asn_PER_type_slss_TxMultiFreq_r15_constr_31, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_slss_TxMultiFreq_r15_specs_31	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_slss_TxDisabled_r15_value2enum_33[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_slss_TxDisabled_r15_enum2value_33[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_slss_TxDisabled_r15_specs_33 = {
	asn_MAP_slss_TxDisabled_r15_value2enum_33,	/* "tag" => N; sorted by tag */
	asn_MAP_slss_TxDisabled_r15_enum2value_33,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_slss_TxDisabled_r15_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_slss_TxDisabled_r15_33 = {
	"slss-TxDisabled-r15",
	"slss-TxDisabled-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_slss_TxDisabled_r15_tags_33,
	sizeof(asn_DEF_slss_TxDisabled_r15_tags_33)
		/sizeof(asn_DEF_slss_TxDisabled_r15_tags_33[0]) - 1, /* 1 */
	asn_DEF_slss_TxDisabled_r15_tags_33,	/* Same as above */
	sizeof(asn_DEF_slss_TxDisabled_r15_tags_33)
		/sizeof(asn_DEF_slss_TxDisabled_r15_tags_33[0]), /* 2 */
	{ 0, &asn_PER_type_slss_TxDisabled_r15_constr_33, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_slss_TxDisabled_r15_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SL_V2X_ConfigDedicated_r14_1[] = {
	{ ATF_POINTER, 10, offsetof(struct SL_V2X_ConfigDedicated_r14, commTxResources_r14),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_commTxResources_r14_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commTxResources-r14"
		},
	{ ATF_POINTER, 9, offsetof(struct SL_V2X_ConfigDedicated_r14, v2x_InterFreqInfoList_r14),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_InterFreqInfoListV2X_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2x-InterFreqInfoList-r14"
		},
	{ ATF_POINTER, 8, offsetof(struct SL_V2X_ConfigDedicated_r14, thresSL_TxPrioritization_r14),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_Priority_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"thresSL-TxPrioritization-r14"
		},
	{ ATF_POINTER, 7, offsetof(struct SL_V2X_ConfigDedicated_r14, typeTxSync_r14),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_TypeTxSync_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"typeTxSync-r14"
		},
	{ ATF_POINTER, 6, offsetof(struct SL_V2X_ConfigDedicated_r14, cbr_DedicatedTxConfigList_r14),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_CBR_CommonTxConfigList_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cbr-DedicatedTxConfigList-r14"
		},
	{ ATF_POINTER, 5, offsetof(struct SL_V2X_ConfigDedicated_r14, commTxResources_v1530),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_commTxResources_v1530_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"commTxResources-v1530"
		},
	{ ATF_POINTER, 4, offsetof(struct SL_V2X_ConfigDedicated_r14, v2x_PacketDuplicationConfig_r15),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_V2X_PacketDuplicationConfig_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"v2x-PacketDuplicationConfig-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct SL_V2X_ConfigDedicated_r14, syncFreqList_r15),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SL_V2X_SyncFreqList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"syncFreqList-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct SL_V2X_ConfigDedicated_r14, slss_TxMultiFreq_r15),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_slss_TxMultiFreq_r15_31,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"slss-TxMultiFreq-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct SL_V2X_ConfigDedicated_r14, slss_TxDisabled_r15),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_slss_TxDisabled_r15_33,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"slss-TxDisabled-r15"
		},
};
static const int asn_MAP_SL_V2X_ConfigDedicated_r14_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_SL_V2X_ConfigDedicated_r14_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SL_V2X_ConfigDedicated_r14_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* commTxResources-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* v2x-InterFreqInfoList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* thresSL-TxPrioritization-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* typeTxSync-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* cbr-DedicatedTxConfigList-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* commTxResources-v1530 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* v2x-PacketDuplicationConfig-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* syncFreqList-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* slss-TxMultiFreq-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* slss-TxDisabled-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_SL_V2X_ConfigDedicated_r14_specs_1 = {
	sizeof(struct SL_V2X_ConfigDedicated_r14),
	offsetof(struct SL_V2X_ConfigDedicated_r14, _asn_ctx),
	asn_MAP_SL_V2X_ConfigDedicated_r14_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_SL_V2X_ConfigDedicated_r14_oms_1,	/* Optional members */
	5, 5,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SL_V2X_ConfigDedicated_r14 = {
	"SL-V2X-ConfigDedicated-r14",
	"SL-V2X-ConfigDedicated-r14",
	&asn_OP_SEQUENCE,
	asn_DEF_SL_V2X_ConfigDedicated_r14_tags_1,
	sizeof(asn_DEF_SL_V2X_ConfigDedicated_r14_tags_1)
		/sizeof(asn_DEF_SL_V2X_ConfigDedicated_r14_tags_1[0]), /* 1 */
	asn_DEF_SL_V2X_ConfigDedicated_r14_tags_1,	/* Same as above */
	sizeof(asn_DEF_SL_V2X_ConfigDedicated_r14_tags_1)
		/sizeof(asn_DEF_SL_V2X_ConfigDedicated_r14_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SL_V2X_ConfigDedicated_r14_1,
	10,	/* Elements count */
	&asn_SPC_SL_V2X_ConfigDedicated_r14_specs_1	/* Additional specs */
};

