/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_VarLogMeasConfig_r15_H_
#define	_VarLogMeasConfig_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LoggingDuration-r10.h"
#include "LoggingInterval-r10.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AreaConfiguration_r10;
struct AreaConfiguration_v1130;
struct TargetMBSFN_AreaList_r12;
struct BT_NameList_r15;
struct WLAN_NameList_r15;

/* VarLogMeasConfig-r15 */
typedef struct VarLogMeasConfig_r15 {
	struct AreaConfiguration_r10	*areaConfiguration_r10	/* OPTIONAL */;
	struct AreaConfiguration_v1130	*areaConfiguration_v1130	/* OPTIONAL */;
	LoggingDuration_r10_t	 loggingDuration_r10;
	LoggingInterval_r10_t	 loggingInterval_r10;
	struct TargetMBSFN_AreaList_r12	*targetMBSFN_AreaList_r12	/* OPTIONAL */;
	struct BT_NameList_r15	*bt_NameList_r15	/* OPTIONAL */;
	struct WLAN_NameList_r15	*wlan_NameList_r15	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarLogMeasConfig_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarLogMeasConfig_r15;

#ifdef __cplusplus
}
#endif

#endif	/* _VarLogMeasConfig_r15_H_ */
#include <asn_internal.h>
