/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_AS_Config_v13c0_H_
#define	_AS_Config_v13c0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RadioResourceConfigDedicated_v1370;
struct RadioResourceConfigDedicated_v13c0;
struct SCellToAddModList_v13c0;
struct SCellToAddModListExt_v13c0;

/* AS-Config-v13c0 */
typedef struct AS_Config_v13c0 {
	struct RadioResourceConfigDedicated_v1370	*radioResourceConfigDedicated_v13c01	/* OPTIONAL */;
	struct RadioResourceConfigDedicated_v13c0	*radioResourceConfigDedicated_v13c02	/* OPTIONAL */;
	struct SCellToAddModList_v13c0	*sCellToAddModList_v13c0	/* OPTIONAL */;
	struct SCellToAddModListExt_v13c0	*sCellToAddModListExt_v13c0	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Config_v13c0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Config_v13c0;
extern asn_SEQUENCE_specifics_t asn_SPC_AS_Config_v13c0_specs_1;
extern asn_TYPE_member_t asn_MBR_AS_Config_v13c0_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _AS_Config_v13c0_H_ */
#include <asn_internal.h>
