/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_BlackCellsToAddMod_H_
#define	_BlackCellsToAddMod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "PhysCellIdRange.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BlackCellsToAddMod */
typedef struct BlackCellsToAddMod {
	long	 cellIndex;
	PhysCellIdRange_t	 physCellIdRange;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BlackCellsToAddMod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BlackCellsToAddMod;
extern asn_SEQUENCE_specifics_t asn_SPC_BlackCellsToAddMod_specs_1;
extern asn_TYPE_member_t asn_MBR_BlackCellsToAddMod_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _BlackCellsToAddMod_H_ */
#include <asn_internal.h>
