/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_InterFreqNeighCellInfo_NB_v1530_H_
#define	_InterFreqNeighCellInfo_NB_v1530_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NSSS_RRM_Config_NB_r15;

/* InterFreqNeighCellInfo-NB-v1530 */
typedef struct InterFreqNeighCellInfo_NB_v1530 {
	struct NSSS_RRM_Config_NB_r15	*nsss_RRM_Config_r15	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterFreqNeighCellInfo_NB_v1530_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFreqNeighCellInfo_NB_v1530;
extern asn_SEQUENCE_specifics_t asn_SPC_InterFreqNeighCellInfo_NB_v1530_specs_1;
extern asn_TYPE_member_t asn_MBR_InterFreqNeighCellInfo_NB_v1530_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _InterFreqNeighCellInfo_NB_v1530_H_ */
#include <asn_internal.h>
