/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "MeasConfig.h"

#include "MeasObjectToRemoveList.h"
#include "MeasObjectToAddModList.h"
#include "ReportConfigToRemoveList.h"
#include "ReportConfigToAddModList.h"
#include "MeasIdToRemoveList.h"
#include "MeasIdToAddModList.h"
#include "QuantityConfig.h"
#include "MeasGapConfig.h"
#include "PreRegistrationInfoHRPD.h"
#include "MeasObjectToAddModList-v9e0.h"
#include "MeasIdToRemoveListExt-r12.h"
#include "MeasIdToAddModListExt-r12.h"
#include "MeasObjectToRemoveListExt-r13.h"
#include "MeasObjectToAddModListExt-r13.h"
#include "MeasIdToAddModList-v1310.h"
#include "MeasIdToAddModListExt-v1310.h"
#include "MeasGapConfigPerCC-List-r14.h"
#include "MeasGapSharingConfig-r14.h"
#include "MeasGapConfigDensePRS-r15.h"
static int
memb_setup_constraint_35(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 31)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_speedStatePars_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_measScaleFactor_r12_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_setup_constr_37 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  31 }	/* (0..31) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_heightThreshRef_r15_constr_35 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_setup_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__speedStatePars__setup, mobilityStateParameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MobilityStateParameters,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mobilityStateParameters"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__speedStatePars__setup, timeToTrigger_SF),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedStateScaleFactors,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeToTrigger-SF"
		},
};
static const ber_tlv_tag_t asn_DEF_setup_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_setup_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mobilityStateParameters */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* timeToTrigger-SF */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_14 = {
	sizeof(struct MeasConfig__speedStatePars__setup),
	offsetof(struct MeasConfig__speedStatePars__setup, _asn_ctx),
	asn_MAP_setup_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_14 = {
	"setup",
	"setup",
	&asn_OP_SEQUENCE,
	asn_DEF_setup_tags_14,
	sizeof(asn_DEF_setup_tags_14)
		/sizeof(asn_DEF_setup_tags_14[0]) - 1, /* 1 */
	asn_DEF_setup_tags_14,	/* Same as above */
	sizeof(asn_DEF_setup_tags_14)
		/sizeof(asn_DEF_setup_tags_14[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_setup_14,
	2,	/* Elements count */
	&asn_SPC_setup_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_speedStatePars_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__speedStatePars, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__speedStatePars, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_speedStatePars_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_speedStatePars_specs_12 = {
	sizeof(struct MeasConfig__speedStatePars),
	offsetof(struct MeasConfig__speedStatePars, _asn_ctx),
	offsetof(struct MeasConfig__speedStatePars, present),
	sizeof(((struct MeasConfig__speedStatePars *)0)->present),
	asn_MAP_speedStatePars_tag2el_12,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_speedStatePars_12 = {
	"speedStatePars",
	"speedStatePars",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_speedStatePars_constr_12, CHOICE_constraint },
	asn_MBR_speedStatePars_12,
	2,	/* Elements count */
	&asn_SPC_speedStatePars_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measScaleFactor_r12_20[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__measScaleFactor_r12, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__measScaleFactor_r12, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasScaleFactor_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_measScaleFactor_r12_tag2el_20[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_measScaleFactor_r12_specs_20 = {
	sizeof(struct MeasConfig__measScaleFactor_r12),
	offsetof(struct MeasConfig__measScaleFactor_r12, _asn_ctx),
	offsetof(struct MeasConfig__measScaleFactor_r12, present),
	sizeof(((struct MeasConfig__measScaleFactor_r12 *)0)->present),
	asn_MAP_measScaleFactor_r12_tag2el_20,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measScaleFactor_r12_20 = {
	"measScaleFactor-r12",
	"measScaleFactor-r12",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_measScaleFactor_r12_constr_20, CHOICE_constraint },
	asn_MBR_measScaleFactor_r12_20,
	2,	/* Elements count */
	&asn_SPC_measScaleFactor_r12_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_heightThreshRef_r15_35[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__heightThreshRef_r15, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasConfig__heightThreshRef_r15, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_setup_constr_37,  memb_setup_constraint_35 },
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_heightThreshRef_r15_tag2el_35[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_heightThreshRef_r15_specs_35 = {
	sizeof(struct MeasConfig__heightThreshRef_r15),
	offsetof(struct MeasConfig__heightThreshRef_r15, _asn_ctx),
	offsetof(struct MeasConfig__heightThreshRef_r15, present),
	sizeof(((struct MeasConfig__heightThreshRef_r15 *)0)->present),
	asn_MAP_heightThreshRef_r15_tag2el_35,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_heightThreshRef_r15_35 = {
	"heightThreshRef-r15",
	"heightThreshRef-r15",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_heightThreshRef_r15_constr_35, CHOICE_constraint },
	asn_MBR_heightThreshRef_r15_35,
	2,	/* Elements count */
	&asn_SPC_heightThreshRef_r15_specs_35	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MeasConfig_1[] = {
	{ ATF_POINTER, 27, offsetof(struct MeasConfig, measObjectToRemoveList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasObjectToRemoveList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measObjectToRemoveList"
		},
	{ ATF_POINTER, 26, offsetof(struct MeasConfig, measObjectToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasObjectToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measObjectToAddModList"
		},
	{ ATF_POINTER, 25, offsetof(struct MeasConfig, reportConfigToRemoveList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportConfigToRemoveList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportConfigToRemoveList"
		},
	{ ATF_POINTER, 24, offsetof(struct MeasConfig, reportConfigToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportConfigToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportConfigToAddModList"
		},
	{ ATF_POINTER, 23, offsetof(struct MeasConfig, measIdToRemoveList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasIdToRemoveList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measIdToRemoveList"
		},
	{ ATF_POINTER, 22, offsetof(struct MeasConfig, measIdToAddModList),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasIdToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measIdToAddModList"
		},
	{ ATF_POINTER, 21, offsetof(struct MeasConfig, quantityConfig),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QuantityConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"quantityConfig"
		},
	{ ATF_POINTER, 20, offsetof(struct MeasConfig, measGapConfig),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MeasGapConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measGapConfig"
		},
	{ ATF_POINTER, 19, offsetof(struct MeasConfig, s_Measure),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"s-Measure"
		},
	{ ATF_POINTER, 18, offsetof(struct MeasConfig, preRegistrationInfoHRPD),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PreRegistrationInfoHRPD,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"preRegistrationInfoHRPD"
		},
	{ ATF_POINTER, 17, offsetof(struct MeasConfig, speedStatePars),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_speedStatePars_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speedStatePars"
		},
	{ ATF_POINTER, 16, offsetof(struct MeasConfig, measObjectToAddModList_v9e0),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasObjectToAddModList_v9e0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measObjectToAddModList-v9e0"
		},
	{ ATF_POINTER, 15, offsetof(struct MeasConfig, allowInterruptions_r11),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allowInterruptions-r11"
		},
	{ ATF_POINTER, 14, offsetof(struct MeasConfig, measScaleFactor_r12),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_measScaleFactor_r12_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measScaleFactor-r12"
		},
	{ ATF_POINTER, 13, offsetof(struct MeasConfig, measIdToRemoveListExt_r12),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasIdToRemoveListExt_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measIdToRemoveListExt-r12"
		},
	{ ATF_POINTER, 12, offsetof(struct MeasConfig, measIdToAddModListExt_r12),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasIdToAddModListExt_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measIdToAddModListExt-r12"
		},
	{ ATF_POINTER, 11, offsetof(struct MeasConfig, measRSRQ_OnAllSymbols_r12),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measRSRQ-OnAllSymbols-r12"
		},
	{ ATF_POINTER, 10, offsetof(struct MeasConfig, measObjectToRemoveListExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasObjectToRemoveListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measObjectToRemoveListExt-r13"
		},
	{ ATF_POINTER, 9, offsetof(struct MeasConfig, measObjectToAddModListExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasObjectToAddModListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measObjectToAddModListExt-r13"
		},
	{ ATF_POINTER, 8, offsetof(struct MeasConfig, measIdToAddModList_v1310),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasIdToAddModList_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measIdToAddModList-v1310"
		},
	{ ATF_POINTER, 7, offsetof(struct MeasConfig, measIdToAddModListExt_v1310),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasIdToAddModListExt_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measIdToAddModListExt-v1310"
		},
	{ ATF_POINTER, 6, offsetof(struct MeasConfig, measGapConfigPerCC_List_r14),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MeasGapConfigPerCC_List_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measGapConfigPerCC-List-r14"
		},
	{ ATF_POINTER, 5, offsetof(struct MeasConfig, measGapSharingConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MeasGapSharingConfig_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measGapSharingConfig-r14"
		},
	{ ATF_POINTER, 4, offsetof(struct MeasConfig, fr1_Gap_r15),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fr1-Gap-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct MeasConfig, mgta_r15),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mgta-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasConfig, measGapConfigDensePRS_r15),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MeasGapConfigDensePRS_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measGapConfigDensePRS-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasConfig, heightThreshRef_r15),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_heightThreshRef_r15_35,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"heightThreshRef-r15"
		},
};
static const int asn_MAP_MeasConfig_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 };
static const ber_tlv_tag_t asn_DEF_MeasConfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasConfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measObjectToRemoveList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measObjectToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reportConfigToRemoveList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* reportConfigToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* measIdToRemoveList */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* measIdToAddModList */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* quantityConfig */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* measGapConfig */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* s-Measure */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* preRegistrationInfoHRPD */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* speedStatePars */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* measObjectToAddModList-v9e0 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* allowInterruptions-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* measScaleFactor-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* measIdToRemoveListExt-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* measIdToAddModListExt-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* measRSRQ-OnAllSymbols-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* measObjectToRemoveListExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* measObjectToAddModListExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* measIdToAddModList-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* measIdToAddModListExt-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* measGapConfigPerCC-List-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* measGapSharingConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* fr1-Gap-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* mgta-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* measGapConfigDensePRS-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 } /* heightThreshRef-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasConfig_specs_1 = {
	sizeof(struct MeasConfig),
	offsetof(struct MeasConfig, _asn_ctx),
	asn_MAP_MeasConfig_tag2el_1,
	27,	/* Count of tags in the map */
	asn_MAP_MeasConfig_oms_1,	/* Optional members */
	11, 16,	/* Root/Additions */
	11,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasConfig = {
	"MeasConfig",
	"MeasConfig",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasConfig_tags_1,
	sizeof(asn_DEF_MeasConfig_tags_1)
		/sizeof(asn_DEF_MeasConfig_tags_1[0]), /* 1 */
	asn_DEF_MeasConfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasConfig_tags_1)
		/sizeof(asn_DEF_MeasConfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasConfig_1,
	27,	/* Elements count */
	&asn_SPC_MeasConfig_specs_1	/* Additional specs */
};

