/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_NPRACH_ConfigSIB_NB_v1550_H_
#define	_NPRACH_ConfigSIB_NB_v1550_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NPRACH-ParametersListTDD-NB-v1550.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NPRACH-ConfigSIB-NB-v1550 */
typedef struct NPRACH_ConfigSIB_NB_v1550 {
	struct NPRACH_ConfigSIB_NB_v1550__tdd_Parameters_v1550 {
		NPRACH_ParametersListTDD_NB_v1550_t	 nprach_ParametersListTDD_v1550;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tdd_Parameters_v1550;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPRACH_ConfigSIB_NB_v1550_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPRACH_ConfigSIB_NB_v1550;
extern asn_SEQUENCE_specifics_t asn_SPC_NPRACH_ConfigSIB_NB_v1550_specs_1;
extern asn_TYPE_member_t asn_MBR_NPRACH_ConfigSIB_NB_v1550_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _NPRACH_ConfigSIB_NB_v1550_H_ */
#include <asn_internal.h>
