/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "RadioResourceConfigCommonSIB.h"

#include "UplinkPowerControlCommon-v1020.h"
#include "RACH-ConfigCommon-v1250.h"
#include "PUSCH-ConfigCommon-v1270.h"
#include "BCCH-Config-v1310.h"
#include "PCCH-Config-v1310.h"
#include "FreqHoppingParameters-r13.h"
#include "PDSCH-ConfigCommon-v1310.h"
#include "PUSCH-ConfigCommon-v1310.h"
#include "PRACH-ConfigSIB-v1310.h"
#include "PUCCH-ConfigCommon-v1310.h"
#include "HighSpeedConfig-r14.h"
#include "PRACH-Config-v1430.h"
#include "PUCCH-ConfigCommon-v1430.h"
#include "PRACH-ConfigSIB-v1530.h"
#include "RSS-Config-r15.h"
#include "WUS-Config-r15.h"
#include "HighSpeedConfig-v1530.h"
#include "UplinkPowerControlCommon-v1530.h"
#include "WUS-Config-v1560.h"
asn_TYPE_member_t asn_MBR_RadioResourceConfigCommonSIB_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, rach_ConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RACH_ConfigCommon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rach-ConfigCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, bcch_Config),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BCCH_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bcch-Config"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, pcch_Config),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PCCH_Config,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcch-Config"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, prach_Config),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRACH_ConfigSIB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prach-Config"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, pdsch_ConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_ConfigCommon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-ConfigCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, pusch_ConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigCommon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, pucch_ConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigCommon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, soundingRS_UL_ConfigCommon),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SoundingRS_UL_ConfigCommon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"soundingRS-UL-ConfigCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, uplinkPowerControlCommon),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlCommon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlCommon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RadioResourceConfigCommonSIB, ul_CyclicPrefixLength),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_CyclicPrefixLength,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-CyclicPrefixLength"
		},
	{ ATF_POINTER, 19, offsetof(struct RadioResourceConfigCommonSIB, uplinkPowerControlCommon_v1020),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlCommon_v1020,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlCommon-v1020"
		},
	{ ATF_POINTER, 18, offsetof(struct RadioResourceConfigCommonSIB, rach_ConfigCommon_v1250),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RACH_ConfigCommon_v1250,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rach-ConfigCommon-v1250"
		},
	{ ATF_POINTER, 17, offsetof(struct RadioResourceConfigCommonSIB, pusch_ConfigCommon_v1270),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigCommon_v1270,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigCommon-v1270"
		},
	{ ATF_POINTER, 16, offsetof(struct RadioResourceConfigCommonSIB, bcch_Config_v1310),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BCCH_Config_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bcch-Config-v1310"
		},
	{ ATF_POINTER, 15, offsetof(struct RadioResourceConfigCommonSIB, pcch_Config_v1310),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PCCH_Config_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcch-Config-v1310"
		},
	{ ATF_POINTER, 14, offsetof(struct RadioResourceConfigCommonSIB, freqHoppingParameters_r13),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreqHoppingParameters_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"freqHoppingParameters-r13"
		},
	{ ATF_POINTER, 13, offsetof(struct RadioResourceConfigCommonSIB, pdsch_ConfigCommon_v1310),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDSCH_ConfigCommon_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdsch-ConfigCommon-v1310"
		},
	{ ATF_POINTER, 12, offsetof(struct RadioResourceConfigCommonSIB, pusch_ConfigCommon_v1310),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUSCH_ConfigCommon_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pusch-ConfigCommon-v1310"
		},
	{ ATF_POINTER, 11, offsetof(struct RadioResourceConfigCommonSIB, prach_ConfigCommon_v1310),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRACH_ConfigSIB_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prach-ConfigCommon-v1310"
		},
	{ ATF_POINTER, 10, offsetof(struct RadioResourceConfigCommonSIB, pucch_ConfigCommon_v1310),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigCommon_v1310,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigCommon-v1310"
		},
	{ ATF_POINTER, 9, offsetof(struct RadioResourceConfigCommonSIB, highSpeedConfig_r14),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HighSpeedConfig_r14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"highSpeedConfig-r14"
		},
	{ ATF_POINTER, 8, offsetof(struct RadioResourceConfigCommonSIB, prach_Config_v1430),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRACH_Config_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prach-Config-v1430"
		},
	{ ATF_POINTER, 7, offsetof(struct RadioResourceConfigCommonSIB, pucch_ConfigCommon_v1430),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PUCCH_ConfigCommon_v1430,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pucch-ConfigCommon-v1430"
		},
	{ ATF_POINTER, 6, offsetof(struct RadioResourceConfigCommonSIB, prach_Config_v1530),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRACH_ConfigSIB_v1530,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prach-Config-v1530"
		},
	{ ATF_POINTER, 5, offsetof(struct RadioResourceConfigCommonSIB, ce_RSS_Config_r15),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSS_Config_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ce-RSS-Config-r15"
		},
	{ ATF_POINTER, 4, offsetof(struct RadioResourceConfigCommonSIB, wus_Config_r15),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WUS_Config_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"wus-Config-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct RadioResourceConfigCommonSIB, highSpeedConfig_v1530),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HighSpeedConfig_v1530,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"highSpeedConfig-v1530"
		},
	{ ATF_POINTER, 2, offsetof(struct RadioResourceConfigCommonSIB, uplinkPowerControlCommon_v1540),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkPowerControlCommon_v1530,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uplinkPowerControlCommon-v1540"
		},
	{ ATF_POINTER, 1, offsetof(struct RadioResourceConfigCommonSIB, wus_Config_v1560),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WUS_Config_v1560,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"wus-Config-v1560"
		},
};
static const int asn_MAP_RadioResourceConfigCommonSIB_oms_1[] = { 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28 };
static const ber_tlv_tag_t asn_DEF_RadioResourceConfigCommonSIB_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RadioResourceConfigCommonSIB_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rach-ConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* bcch-Config */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pcch-Config */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* prach-Config */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* pdsch-ConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* pusch-ConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* pucch-ConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* soundingRS-UL-ConfigCommon */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* uplinkPowerControlCommon */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* ul-CyclicPrefixLength */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* uplinkPowerControlCommon-v1020 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* rach-ConfigCommon-v1250 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* pusch-ConfigCommon-v1270 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* bcch-Config-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* pcch-Config-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* freqHoppingParameters-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* pdsch-ConfigCommon-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* pusch-ConfigCommon-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* prach-ConfigCommon-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* pucch-ConfigCommon-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* highSpeedConfig-r14 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* prach-Config-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* pucch-ConfigCommon-v1430 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* prach-Config-v1530 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* ce-RSS-Config-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* wus-Config-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* highSpeedConfig-v1530 */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* uplinkPowerControlCommon-v1540 */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 } /* wus-Config-v1560 */
};
asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigCommonSIB_specs_1 = {
	sizeof(struct RadioResourceConfigCommonSIB),
	offsetof(struct RadioResourceConfigCommonSIB, _asn_ctx),
	asn_MAP_RadioResourceConfigCommonSIB_tag2el_1,
	29,	/* Count of tags in the map */
	asn_MAP_RadioResourceConfigCommonSIB_oms_1,	/* Optional members */
	0, 19,	/* Root/Additions */
	10,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigCommonSIB = {
	"RadioResourceConfigCommonSIB",
	"RadioResourceConfigCommonSIB",
	&asn_OP_SEQUENCE,
	asn_DEF_RadioResourceConfigCommonSIB_tags_1,
	sizeof(asn_DEF_RadioResourceConfigCommonSIB_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigCommonSIB_tags_1[0]), /* 1 */
	asn_DEF_RadioResourceConfigCommonSIB_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadioResourceConfigCommonSIB_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigCommonSIB_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RadioResourceConfigCommonSIB_1,
	29,	/* Elements count */
	&asn_SPC_RadioResourceConfigCommonSIB_specs_1	/* Additional specs */
};

