/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "UL-CarrierConfigDedicated-NB-r13.h"

#include "CarrierFreq-NB-r13.h"
asn_TYPE_member_t asn_MBR_UL_CarrierConfigDedicated_NB_r13_1[] = {
	{ ATF_POINTER, 2, offsetof(struct UL_CarrierConfigDedicated_NB_r13, ul_CarrierFreq_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CarrierFreq_NB_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-CarrierFreq-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct UL_CarrierConfigDedicated_NB_r13, tdd_UL_DL_AlignmentOffset_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TDD_UL_DL_AlignmentOffset_NB_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdd-UL-DL-AlignmentOffset-r15"
		},
};
static const int asn_MAP_UL_CarrierConfigDedicated_NB_r13_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_UL_CarrierConfigDedicated_NB_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UL_CarrierConfigDedicated_NB_r13_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-CarrierFreq-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd-UL-DL-AlignmentOffset-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_UL_CarrierConfigDedicated_NB_r13_specs_1 = {
	sizeof(struct UL_CarrierConfigDedicated_NB_r13),
	offsetof(struct UL_CarrierConfigDedicated_NB_r13, _asn_ctx),
	asn_MAP_UL_CarrierConfigDedicated_NB_r13_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_UL_CarrierConfigDedicated_NB_r13_oms_1,	/* Optional members */
	1, 1,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UL_CarrierConfigDedicated_NB_r13 = {
	"UL-CarrierConfigDedicated-NB-r13",
	"UL-CarrierConfigDedicated-NB-r13",
	&asn_OP_SEQUENCE,
	asn_DEF_UL_CarrierConfigDedicated_NB_r13_tags_1,
	sizeof(asn_DEF_UL_CarrierConfigDedicated_NB_r13_tags_1)
		/sizeof(asn_DEF_UL_CarrierConfigDedicated_NB_r13_tags_1[0]), /* 1 */
	asn_DEF_UL_CarrierConfigDedicated_NB_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_UL_CarrierConfigDedicated_NB_r13_tags_1)
		/sizeof(asn_DEF_UL_CarrierConfigDedicated_NB_r13_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UL_CarrierConfigDedicated_NB_r13_1,
	2,	/* Elements count */
	&asn_SPC_UL_CarrierConfigDedicated_NB_r13_specs_1	/* Additional specs */
};

