/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_UL_ConfigCommon_NB_r14_H_
#define	_UL_ConfigCommon_NB_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CarrierFreq-NB-r13.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NPRACH_ParametersList_NB_r14;

/* UL-ConfigCommon-NB-r14 */
typedef struct UL_ConfigCommon_NB_r14 {
	CarrierFreq_NB_r13_t	 ul_CarrierFreq_r14;
	struct NPRACH_ParametersList_NB_r14	*nprach_ParametersList_r14	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct NPRACH_ParametersList_NB_r14	*nprach_ParametersListEDT_r15	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_ConfigCommon_NB_r14_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_ConfigCommon_NB_r14;
extern asn_SEQUENCE_specifics_t asn_SPC_UL_ConfigCommon_NB_r14_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_ConfigCommon_NB_r14_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UL_ConfigCommon_NB_r14_H_ */
#include <asn_internal.h>
