/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-UE-Variables"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_VarShortResumeMAC_Input_NB_r13_H_
#define	_VarShortResumeMAC_Input_NB_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VarShortResumeMAC-Input-r13.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VarShortResumeMAC-Input-NB-r13 */
typedef VarShortResumeMAC_Input_r13_t	 VarShortResumeMAC_Input_NB_r13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarShortResumeMAC_Input_NB_r13;
asn_struct_free_f VarShortResumeMAC_Input_NB_r13_free;
asn_struct_print_f VarShortResumeMAC_Input_NB_r13_print;
asn_constr_check_f VarShortResumeMAC_Input_NB_r13_constraint;
ber_type_decoder_f VarShortResumeMAC_Input_NB_r13_decode_ber;
der_type_encoder_f VarShortResumeMAC_Input_NB_r13_encode_der;
xer_type_decoder_f VarShortResumeMAC_Input_NB_r13_decode_xer;
xer_type_encoder_f VarShortResumeMAC_Input_NB_r13_encode_xer;
per_type_decoder_f VarShortResumeMAC_Input_NB_r13_decode_uper;
per_type_encoder_f VarShortResumeMAC_Input_NB_r13_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VarShortResumeMAC_Input_NB_r13_H_ */
#include <asn_internal.h>
