/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_AS_Config_v1320_H_
#define	_AS_Config_v1320_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SCellToAddModListExt_r13;
struct RCLWI_Configuration_r13;

/* AS-Config-v1320 */
typedef struct AS_Config_v1320 {
	struct SCellToAddModListExt_r13	*sourceSCellConfigList_r13	/* OPTIONAL */;
	struct RCLWI_Configuration_r13	*sourceRCLWI_Configuration_r13	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AS_Config_v1320_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AS_Config_v1320;
extern asn_SEQUENCE_specifics_t asn_SPC_AS_Config_v1320_specs_1;
extern asn_TYPE_member_t asn_MBR_AS_Config_v1320_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AS_Config_v1320_H_ */
#include <asn_internal.h>
