/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "RadioResourceConfigDedicatedSCG-r12.h"

#include "DRB-ToAddModListSCG-r12.h"
#include "MAC-MainConfig.h"
#include "RLF-TimersAndConstantsSCG-r12.h"
#include "DRB-ToAddModListSCG-r15.h"
#include "SRB-ToAddModList.h"
#include "SRB-ToReleaseList-r15.h"
#include "DRB-ToReleaseList-r15.h"
asn_TYPE_member_t asn_MBR_RadioResourceConfigDedicatedSCG_r12_1[] = {
	{ ATF_POINTER, 7, offsetof(struct RadioResourceConfigDedicatedSCG_r12, drb_ToAddModListSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToAddModListSCG_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToAddModListSCG-r12"
		},
	{ ATF_POINTER, 6, offsetof(struct RadioResourceConfigDedicatedSCG_r12, mac_MainConfigSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAC_MainConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mac-MainConfigSCG-r12"
		},
	{ ATF_POINTER, 5, offsetof(struct RadioResourceConfigDedicatedSCG_r12, rlf_TimersAndConstantsSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_RLF_TimersAndConstantsSCG_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rlf-TimersAndConstantsSCG-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct RadioResourceConfigDedicatedSCG_r12, drb_ToAddModListSCG_r15),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToAddModListSCG_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToAddModListSCG-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct RadioResourceConfigDedicatedSCG_r12, srb_ToAddModListSCG_r15),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRB_ToAddModList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srb-ToAddModListSCG-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct RadioResourceConfigDedicatedSCG_r12, srb_ToReleaseListSCG_r15),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRB_ToReleaseList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srb-ToReleaseListSCG-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct RadioResourceConfigDedicatedSCG_r12, drb_ToReleaseListSCG_r15),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ToReleaseList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"drb-ToReleaseListSCG-r15"
		},
};
static const int asn_MAP_RadioResourceConfigDedicatedSCG_r12_oms_1[] = { 0, 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_RadioResourceConfigDedicatedSCG_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RadioResourceConfigDedicatedSCG_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* drb-ToAddModListSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* mac-MainConfigSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rlf-TimersAndConstantsSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* drb-ToAddModListSCG-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* srb-ToAddModListSCG-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* srb-ToReleaseListSCG-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* drb-ToReleaseListSCG-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_RadioResourceConfigDedicatedSCG_r12_specs_1 = {
	sizeof(struct RadioResourceConfigDedicatedSCG_r12),
	offsetof(struct RadioResourceConfigDedicatedSCG_r12, _asn_ctx),
	asn_MAP_RadioResourceConfigDedicatedSCG_r12_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_RadioResourceConfigDedicatedSCG_r12_oms_1,	/* Optional members */
	3, 4,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RadioResourceConfigDedicatedSCG_r12 = {
	"RadioResourceConfigDedicatedSCG-r12",
	"RadioResourceConfigDedicatedSCG-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_RadioResourceConfigDedicatedSCG_r12_tags_1,
	sizeof(asn_DEF_RadioResourceConfigDedicatedSCG_r12_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicatedSCG_r12_tags_1[0]), /* 1 */
	asn_DEF_RadioResourceConfigDedicatedSCG_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_RadioResourceConfigDedicatedSCG_r12_tags_1)
		/sizeof(asn_DEF_RadioResourceConfigDedicatedSCG_r12_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RadioResourceConfigDedicatedSCG_r12_1,
	7,	/* Elements count */
	&asn_SPC_RadioResourceConfigDedicatedSCG_r12_specs_1	/* Additional specs */
};

