/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_RAN_AreaCode_r15_H_
#define	_RAN_AreaCode_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RAN-AreaCode-r15 */
typedef long	 RAN_AreaCode_r15_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RAN_AreaCode_r15_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RAN_AreaCode_r15;
asn_struct_free_f RAN_AreaCode_r15_free;
asn_struct_print_f RAN_AreaCode_r15_print;
asn_constr_check_f RAN_AreaCode_r15_constraint;
ber_type_decoder_f RAN_AreaCode_r15_decode_ber;
der_type_encoder_f RAN_AreaCode_r15_encode_der;
xer_type_decoder_f RAN_AreaCode_r15_decode_xer;
xer_type_encoder_f RAN_AreaCode_r15_encode_xer;
per_type_decoder_f RAN_AreaCode_r15_decode_uper;
per_type_encoder_f RAN_AreaCode_r15_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RAN_AreaCode_r15_H_ */
#include <asn_internal.h>
