/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_RRCConnectionRelease_NB_v1530_IEs_H_
#define	_RRCConnectionRelease_NB_v1530_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "NextHopChainingCount.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionRelease_NB_v1530_IEs__drb_ContinueROHC_r15 {
	RRCConnectionRelease_NB_v1530_IEs__drb_ContinueROHC_r15_true	= 0
} e_RRCConnectionRelease_NB_v1530_IEs__drb_ContinueROHC_r15;

/* Forward declarations */
struct RRCConnectionRelease_NB_v1550_IEs;

/* RRCConnectionRelease-NB-v1530-IEs */
typedef struct RRCConnectionRelease_NB_v1530_IEs {
	long	*drb_ContinueROHC_r15	/* OPTIONAL */;
	NextHopChainingCount_t	*nextHopChainingCount_r15	/* OPTIONAL */;
	struct RRCConnectionRelease_NB_v1550_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_NB_v1530_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_drb_ContinueROHC_r15_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease_NB_v1530_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionRelease_NB_v1530_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionRelease_NB_v1530_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionRelease_NB_v1530_IEs_H_ */
#include <asn_internal.h>
