/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "SCellToAddModListExt-v13c0.h"

#include "SCellToAddMod-v13c0.h"
asn_per_constraints_t asn_PER_type_SCellToAddModListExt_v13c0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  31 }	/* (SIZE(1..31)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SCellToAddModListExt_v13c0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SCellToAddMod_v13c0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_SCellToAddModListExt_v13c0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_SCellToAddModListExt_v13c0_specs_1 = {
	sizeof(struct SCellToAddModListExt_v13c0),
	offsetof(struct SCellToAddModListExt_v13c0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_SCellToAddModListExt_v13c0 = {
	"SCellToAddModListExt-v13c0",
	"SCellToAddModListExt-v13c0",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_SCellToAddModListExt_v13c0_tags_1,
	sizeof(asn_DEF_SCellToAddModListExt_v13c0_tags_1)
		/sizeof(asn_DEF_SCellToAddModListExt_v13c0_tags_1[0]), /* 1 */
	asn_DEF_SCellToAddModListExt_v13c0_tags_1,	/* Same as above */
	sizeof(asn_DEF_SCellToAddModListExt_v13c0_tags_1)
		/sizeof(asn_DEF_SCellToAddModListExt_v13c0_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_SCellToAddModListExt_v13c0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_SCellToAddModListExt_v13c0_1,
	1,	/* Single element */
	&asn_SPC_SCellToAddModListExt_v13c0_specs_1	/* Additional specs */
};

