/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#include "SCG-ConfigPartSCG-r12.h"

#include "RadioResourceConfigDedicatedSCG-r12.h"
#include "SCellToReleaseList-r10.h"
#include "PSCellToAddMod-r12.h"
#include "SCellToAddModList-r10.h"
#include "MobilityControlInfoSCG-r12.h"
#include "SCellToReleaseListExt-r13.h"
#include "SCellToAddModListExt-r13.h"
#include "SCellToAddModListExt-v1370.h"
#include "PSCellToAddMod-v1440.h"
#include "SCellGroupToReleaseList-r15.h"
#include "SCellGroupToAddModList-r15.h"
#include "MeasConfig.h"
#include "TDM-PatternConfig-r15.h"
asn_TYPE_member_t asn_MBR_SCG_ConfigPartSCG_r12_1[] = {
	{ ATF_POINTER, 13, offsetof(struct SCG_ConfigPartSCG_r12, radioResourceConfigDedicatedSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioResourceConfigDedicatedSCG_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radioResourceConfigDedicatedSCG-r12"
		},
	{ ATF_POINTER, 12, offsetof(struct SCG_ConfigPartSCG_r12, sCellToReleaseListSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToReleaseList_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellToReleaseListSCG-r12"
		},
	{ ATF_POINTER, 11, offsetof(struct SCG_ConfigPartSCG_r12, pSCellToAddMod_r12),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PSCellToAddMod_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pSCellToAddMod-r12"
		},
	{ ATF_POINTER, 10, offsetof(struct SCG_ConfigPartSCG_r12, sCellToAddModListSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToAddModList_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellToAddModListSCG-r12"
		},
	{ ATF_POINTER, 9, offsetof(struct SCG_ConfigPartSCG_r12, mobilityControlInfoSCG_r12),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MobilityControlInfoSCG_r12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mobilityControlInfoSCG-r12"
		},
	{ ATF_POINTER, 8, offsetof(struct SCG_ConfigPartSCG_r12, sCellToReleaseListSCG_Ext_r13),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToReleaseListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellToReleaseListSCG-Ext-r13"
		},
	{ ATF_POINTER, 7, offsetof(struct SCG_ConfigPartSCG_r12, sCellToAddModListSCG_Ext_r13),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToAddModListExt_r13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellToAddModListSCG-Ext-r13"
		},
	{ ATF_POINTER, 6, offsetof(struct SCG_ConfigPartSCG_r12, sCellToAddModListSCG_Ext_v1370),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToAddModListExt_v1370,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellToAddModListSCG-Ext-v1370"
		},
	{ ATF_POINTER, 5, offsetof(struct SCG_ConfigPartSCG_r12, pSCellToAddMod_v1440),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PSCellToAddMod_v1440,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pSCellToAddMod-v1440"
		},
	{ ATF_POINTER, 4, offsetof(struct SCG_ConfigPartSCG_r12, sCellGroupToReleaseListSCG_r15),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellGroupToReleaseList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellGroupToReleaseListSCG-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct SCG_ConfigPartSCG_r12, sCellGroupToAddModListSCG_r15),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellGroupToAddModList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sCellGroupToAddModListSCG-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct SCG_ConfigPartSCG_r12, measConfigSN_r15),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measConfigSN-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct SCG_ConfigPartSCG_r12, tdm_PatternConfigNE_DC_r15),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TDM_PatternConfig_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdm-PatternConfigNE-DC-r15"
		},
};
static const int asn_MAP_SCG_ConfigPartSCG_r12_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };
static const ber_tlv_tag_t asn_DEF_SCG_ConfigPartSCG_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SCG_ConfigPartSCG_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radioResourceConfigDedicatedSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sCellToReleaseListSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pSCellToAddMod-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sCellToAddModListSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* mobilityControlInfoSCG-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* sCellToReleaseListSCG-Ext-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* sCellToAddModListSCG-Ext-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* sCellToAddModListSCG-Ext-v1370 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* pSCellToAddMod-v1440 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* sCellGroupToReleaseListSCG-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* sCellGroupToAddModListSCG-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* measConfigSN-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 } /* tdm-PatternConfigNE-DC-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_SCG_ConfigPartSCG_r12_specs_1 = {
	sizeof(struct SCG_ConfigPartSCG_r12),
	offsetof(struct SCG_ConfigPartSCG_r12, _asn_ctx),
	asn_MAP_SCG_ConfigPartSCG_r12_tag2el_1,
	13,	/* Count of tags in the map */
	asn_MAP_SCG_ConfigPartSCG_r12_oms_1,	/* Optional members */
	5, 8,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SCG_ConfigPartSCG_r12 = {
	"SCG-ConfigPartSCG-r12",
	"SCG-ConfigPartSCG-r12",
	&asn_OP_SEQUENCE,
	asn_DEF_SCG_ConfigPartSCG_r12_tags_1,
	sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1)
		/sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1[0]), /* 1 */
	asn_DEF_SCG_ConfigPartSCG_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1)
		/sizeof(asn_DEF_SCG_ConfigPartSCG_r12_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SCG_ConfigPartSCG_r12_1,
	13,	/* Elements count */
	&asn_SPC_SCG_ConfigPartSCG_r12_specs_1	/* Additional specs */
};

