/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SIB_GuardbandInbandSamePCI_TDD_NB_r15_H_
#define	_SIB_GuardbandInbandSamePCI_TDD_NB_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SIB-GuardbandInbandSamePCI-TDD-NB-r15 */
typedef struct SIB_GuardbandInbandSamePCI_TDD_NB_r15 {
	BIT_STRING_t	 spare;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB_GuardbandInbandSamePCI_TDD_NB_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIB_GuardbandInbandSamePCI_TDD_NB_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB_GuardbandInbandSamePCI_TDD_NB_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB_GuardbandInbandSamePCI_TDD_NB_r15_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SIB_GuardbandInbandSamePCI_TDD_NB_r15_H_ */
#include <asn_internal.h>
