/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-Sidelink-Preconf"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SL_V2X_TxProfileList_r15_H_
#define	_SL_V2X_TxProfileList_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SL-V2X-TxProfile-r15.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL-V2X-TxProfileList-r15 */
typedef struct SL_V2X_TxProfileList_r15 {
	A_SEQUENCE_OF(SL_V2X_TxProfile_r15_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_V2X_TxProfileList_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_V2X_TxProfileList_r15;
extern asn_SET_OF_specifics_t asn_SPC_SL_V2X_TxProfileList_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_V2X_TxProfileList_r15_1[1];
extern asn_per_constraints_t asn_PER_type_SL_V2X_TxProfileList_r15_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_V2X_TxProfileList_r15_H_ */
#include <asn_internal.h>
