/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-Sidelink-Preconf"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SL_V2X_Preconfiguration_r14_H_
#define	_SL_V2X_Preconfiguration_r14_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SL-V2X-PreconfigFreqList-r14.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SL_V2X_Preconfiguration_r14__slss_TxMultiFreq_r15 {
	SL_V2X_Preconfiguration_r14__slss_TxMultiFreq_r15_true	= 0
} e_SL_V2X_Preconfiguration_r14__slss_TxMultiFreq_r15;

/* Forward declarations */
struct SL_AnchorCarrierFreqList_V2X_r14;
struct SL_CBR_PreconfigTxConfigList_r14;
struct SL_V2X_PacketDuplicationConfig_r15;
struct SL_V2X_SyncFreqList_r15;
struct SL_V2X_TxProfileList_r15;

/* SL-V2X-Preconfiguration-r14 */
typedef struct SL_V2X_Preconfiguration_r14 {
	SL_V2X_PreconfigFreqList_r14_t	 v2x_PreconfigFreqList_r14;
	struct SL_AnchorCarrierFreqList_V2X_r14	*anchorCarrierFreqList_r14	/* OPTIONAL */;
	struct SL_CBR_PreconfigTxConfigList_r14	*cbr_PreconfigList_r14	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SL_V2X_PacketDuplicationConfig_r15	*v2x_PacketDuplicationConfig_r15	/* OPTIONAL */;
	struct SL_V2X_SyncFreqList_r15	*syncFreqList_r15	/* OPTIONAL */;
	long	*slss_TxMultiFreq_r15	/* OPTIONAL */;
	struct SL_V2X_TxProfileList_r15	*v2x_TxProfileList_r15	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_V2X_Preconfiguration_r14_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_slss_TxMultiFreq_r15_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SL_V2X_Preconfiguration_r14;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_V2X_Preconfiguration_r14_H_ */
#include <asn_internal.h>
