/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_SystemInformationBlockType1_NB_v1430_H_
#define	_SystemInformationBlockType1_NB_v1430_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellSelectionInfo_NB_v1430;
struct SystemInformationBlockType1_NB_v1450;

/* SystemInformationBlockType1-NB-v1430 */
typedef struct SystemInformationBlockType1_NB_v1430 {
	struct CellSelectionInfo_NB_v1430	*cellSelectionInfo_v1430	/* OPTIONAL */;
	struct SystemInformationBlockType1_NB_v1450	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformationBlockType1_NB_v1430_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType1_NB_v1430;
extern asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType1_NB_v1430_specs_1;
extern asn_TYPE_member_t asn_MBR_SystemInformationBlockType1_NB_v1430_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SystemInformationBlockType1_NB_v1430_H_ */
#include <asn_internal.h>
