/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_TDD_UL_DL_AlignmentOffset_NB_r15_H_
#define	_TDD_UL_DL_AlignmentOffset_NB_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TDD_UL_DL_AlignmentOffset_NB_r15 {
	TDD_UL_DL_AlignmentOffset_NB_r15_khz_7dot5	= 0,
	TDD_UL_DL_AlignmentOffset_NB_r15_khz0	= 1,
	TDD_UL_DL_AlignmentOffset_NB_r15_khz7dot5	= 2
} e_TDD_UL_DL_AlignmentOffset_NB_r15;

/* TDD-UL-DL-AlignmentOffset-NB-r15 */
typedef long	 TDD_UL_DL_AlignmentOffset_NB_r15_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TDD_UL_DL_AlignmentOffset_NB_r15_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TDD_UL_DL_AlignmentOffset_NB_r15;
extern const asn_INTEGER_specifics_t asn_SPC_TDD_UL_DL_AlignmentOffset_NB_r15_specs_1;
asn_struct_free_f TDD_UL_DL_AlignmentOffset_NB_r15_free;
asn_struct_print_f TDD_UL_DL_AlignmentOffset_NB_r15_print;
asn_constr_check_f TDD_UL_DL_AlignmentOffset_NB_r15_constraint;
ber_type_decoder_f TDD_UL_DL_AlignmentOffset_NB_r15_decode_ber;
der_type_encoder_f TDD_UL_DL_AlignmentOffset_NB_r15_encode_der;
xer_type_decoder_f TDD_UL_DL_AlignmentOffset_NB_r15_decode_xer;
xer_type_encoder_f TDD_UL_DL_AlignmentOffset_NB_r15_encode_xer;
per_type_decoder_f TDD_UL_DL_AlignmentOffset_NB_r15_decode_uper;
per_type_encoder_f TDD_UL_DL_AlignmentOffset_NB_r15_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TDD_UL_DL_AlignmentOffset_NB_r15_H_ */
#include <asn_internal.h>
