/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_UEInformationResponse_v1530_IEs_H_
#define	_UEInformationResponse_v1530_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultListIdle_r15;
struct FlightPathInfoReport_r15;

/* UEInformationResponse-v1530-IEs */
typedef struct UEInformationResponse_v1530_IEs {
	struct MeasResultListIdle_r15	*measResultListIdle_r15	/* OPTIONAL */;
	struct FlightPathInfoReport_r15	*flightPathInfoReport_r15	/* OPTIONAL */;
	struct UEInformationResponse_v1530_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEInformationResponse_v1530_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEInformationResponse_v1530_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEInformationResponse_v1530_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEInformationResponse_v1530_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UEInformationResponse_v1530_IEs_H_ */
#include <asn_internal.h>
