/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NBIOT-RRC-Definitions"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_UL_CCCH_MessageType_NB_H_
#define	_UL_CCCH_MessageType_NB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCConnectionReestablishmentRequest-NB.h"
#include "RRCConnectionRequest-NB.h"
#include "RRCConnectionResumeRequest-NB.h"
#include "RRCEarlyDataRequest-NB-r15.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_CCCH_MessageType_NB_PR {
	UL_CCCH_MessageType_NB_PR_NOTHING,	/* No components present */
	UL_CCCH_MessageType_NB_PR_c1,
	UL_CCCH_MessageType_NB_PR_messageClassExtension
} UL_CCCH_MessageType_NB_PR;
typedef enum UL_CCCH_MessageType_NB__c1_PR {
	UL_CCCH_MessageType_NB__c1_PR_NOTHING,	/* No components present */
	UL_CCCH_MessageType_NB__c1_PR_rrcConnectionReestablishmentRequest_r13,
	UL_CCCH_MessageType_NB__c1_PR_rrcConnectionRequest_r13,
	UL_CCCH_MessageType_NB__c1_PR_rrcConnectionResumeRequest_r13,
	UL_CCCH_MessageType_NB__c1_PR_rrcEarlyDataRequest_r15
} UL_CCCH_MessageType_NB__c1_PR;

/* UL-CCCH-MessageType-NB */
typedef struct UL_CCCH_MessageType_NB {
	UL_CCCH_MessageType_NB_PR present;
	union UL_CCCH_MessageType_NB_u {
		struct UL_CCCH_MessageType_NB__c1 {
			UL_CCCH_MessageType_NB__c1_PR present;
			union UL_CCCH_MessageType_NB__c1_u {
				RRCConnectionReestablishmentRequest_NB_t	 rrcConnectionReestablishmentRequest_r13;
				RRCConnectionRequest_NB_t	 rrcConnectionRequest_r13;
				RRCConnectionResumeRequest_NB_t	 rrcConnectionResumeRequest_r13;
				RRCEarlyDataRequest_NB_r15_t	 rrcEarlyDataRequest_r15;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} c1;
		struct UL_CCCH_MessageType_NB__messageClassExtension {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} messageClassExtension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_CCCH_MessageType_NB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_CCCH_MessageType_NB;
extern asn_CHOICE_specifics_t asn_SPC_UL_CCCH_MessageType_NB_specs_1;
extern asn_TYPE_member_t asn_MBR_UL_CCCH_MessageType_NB_1[2];
extern asn_per_constraints_t asn_PER_type_UL_CCCH_MessageType_NB_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_CCCH_MessageType_NB_H_ */
#include <asn_internal.h>
