/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "RRC.asn1"
 * 	`asn1c -D ASN1Data -pdu=RRCConnectionSetup -no-gen-OER -no-gen-example -fcompound-names -fno-include-deps`
 */

#ifndef	_VarMeasReport_H_
#define	_VarMeasReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasId.h"
#include "MeasId-v1250.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellsTriggeredList;
struct CSI_RS_TriggeredList_r12;
struct Tx_ResourcePoolMeasList_r14;

/* VarMeasReport */
typedef struct VarMeasReport {
	MeasId_t	 measId;
	MeasId_v1250_t	*measId_v1250	/* OPTIONAL */;
	struct CellsTriggeredList	*cellsTriggeredList	/* OPTIONAL */;
	struct CSI_RS_TriggeredList_r12	*csi_RS_TriggeredList_r12	/* OPTIONAL */;
	struct Tx_ResourcePoolMeasList_r14	*poolsTriggeredList_r14	/* OPTIONAL */;
	long	 numberOfReportsSent;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarMeasReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarMeasReport;
extern asn_SEQUENCE_specifics_t asn_SPC_VarMeasReport_specs_1;
extern asn_TYPE_member_t asn_MBR_VarMeasReport_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _VarMeasReport_H_ */
#include <asn_internal.h>
